# DateTime Extraction

DateTime Extraction is the process of extracting useful information from a date or time column.

A single datetime value can contain many useful features, such as:

- Year
- Month
- Day
- Hour
- Minute
- Second
- Day of Week
- Week of Year
- Quarter
- Day of Year

These extracted features can be used in Exploratory Data Analysis and Machine Learning.

In [1]:
import pandas as pd

df = pd.DataFrame({
    "Date": [
        "2026-01-15 08:30:45",
        "2026-02-20 14:45:30",
        "2026-03-25 18:15:20",
        "2026-04-10 21:00:10",
        "2026-05-05 10:20:55"
    ]
})

df

                  Date
0  2026-01-15 08:30:45
1  2026-02-20 14:45:30
2  2026-03-25 18:15:20
3  2026-04-10 21:00:10
4  2026-05-05 10:20:55

## Converting a Column to Datetime

Before extracting datetime components, we first convert the column into Pandas datetime format.

We use:

`pd.to_datetime()`

This allows us to use the `.dt` accessor for datetime extraction.

In [2]:
df["Date"] = pd.to_datetime(df["Date"])

df

                 Date
0 2026-01-15 08:30:45
1 2026-02-20 14:45:30
2 2026-03-25 18:15:20
3 2026-04-10 21:00:10
4 2026-05-05 10:20:55

In [3]:
df.dtypes

Date    datetime64[us]
dtype: object

## Extracting Year

The year can be extracted using:

`dt.year`

Example:

2026-01-15 → 2026

In [4]:
df["Year"] = df["Date"].dt.year

df

                 Date  Year
0 2026-01-15 08:30:45  2026
1 2026-02-20 14:45:30  2026
2 2026-03-25 18:15:20  2026
3 2026-04-10 21:00:10  2026
4 2026-05-05 10:20:55  2026

## Extracting Month

The month can be extracted using:

`dt.month`

The result is a number from:

1 → January

12 → December

In [5]:
df["Month"] = df["Date"].dt.month

df

                 Date  Year  Month
0 2026-01-15 08:30:45  2026      1
1 2026-02-20 14:45:30  2026      2
2 2026-03-25 18:15:20  2026      3
3 2026-04-10 21:00:10  2026      4
4 2026-05-05 10:20:55  2026      5

In [6]:
df["Month_Name"] = df["Date"].dt.month_name()

df

                 Date  Year  Month Month_Name
0 2026-01-15 08:30:45  2026      1    January
1 2026-02-20 14:45:30  2026      2   February
2 2026-03-25 18:15:20  2026      3      March
3 2026-04-10 21:00:10  2026      4      April
4 2026-05-05 10:20:55  2026      5        May

## Extracting Day

The day of the month can be extracted using:

`dt.day`

For example:

2026-05-05 → 5

In [7]:
df["Day"] = df["Date"].dt.day

df

                 Date  Year  Month Month_Name  Day
0 2026-01-15 08:30:45  2026      1    January   15
1 2026-02-20 14:45:30  2026      2   February   20
2 2026-03-25 18:15:20  2026      3      March   25
3 2026-04-10 21:00:10  2026      4      April   10
4 2026-05-05 10:20:55  2026      5        May    5

## Extracting Day of Week

Pandas represents:

Monday → 0
Tuesday → 1
Wednesday → 2
Thursday → 3
Friday → 4
Saturday → 5
Sunday → 6

This can be useful for identifying weekday and weekend patterns.

In [8]:
df["Day_of_Week"] = df["Date"].dt.dayofweek

df

                 Date  Year  Month Month_Name  Day  Day_of_Week
0 2026-01-15 08:30:45  2026      1    January   15            3
1 2026-02-20 14:45:30  2026      2   February   20            4
2 2026-03-25 18:15:20  2026      3      March   25            2
3 2026-04-10 21:00:10  2026      4      April   10            4
4 2026-05-05 10:20:55  2026      5        May    5            1

In [9]:
df["Day_Name"] = df["Date"].dt.day_name()

df

                 Date  Year  Month Month_Name  Day  Day_of_Week   Day_Name
0 2026-01-15 08:30:45  2026      1    January   15            3   Thursday
1 2026-02-20 14:45:30  2026      2   February   20            4     Friday
2 2026-03-25 18:15:20  2026      3      March   25            2  Wednesday
3 2026-04-10 21:00:10  2026      4      April   10            4     Friday
4 2026-05-05 10:20:55  2026      5        May    5            1    Tuesday

## Extracting Hour

The hour can be extracted using:

`dt.hour`

For example:

08:30:45 → 8

14:45:30 → 14

21:00:10 → 21

In [10]:
df["Hour"] = df["Date"].dt.hour

df

,Date,Year,Month,Month_Name,Day,Day_of_Week,Day_Name,Hour
0,2026-01-15 08:30:45,2026,1,January,15,3,Thursday,8
1,2026-02-20 14:45:30,2026,2,February,20,4,Friday,14
2,2026-03-25 18:15:20,2026,3,March,25,2,Wednesday,18
3,2026-04-10 21:00:10,2026,4,April,10,4,Friday,21
4,2026-05-05 10:20:55,2026,5,May,5,1,Tuesday,10

In [11]:
df["Minute"] = df["Date"].dt.minute

df

,Date,Year,Month,Month_Name,Day,Day_of_Week,Day_Name,Hour,Minute
0,2026-01-15 08:30:45,2026,1,January,15,3,Thursday,8,30
1,2026-02-20 14:45:30,2026,2,February,20,4,Friday,14,45
2,2026-03-25 18:15:20,2026,3,March,25,2,Wednesday,18,15
3,2026-04-10 21:00:10,2026,4,April,10,4,Friday,21,0
4,2026-05-05 10:20:55,2026,5,May,5,1,Tuesday,10,20

In [12]:
df["Second"] = df["Date"].dt.second

df

,Date,Year,Month,Month_Name,Day,Day_of_Week,Day_Name,Hour,Minute,Second
0,2026-01-15 08:30:45,2026,1,January,15,3,Thursday,8,30,45
1,2026-02-20 14:45:30,2026,2,February,20,4,Friday,14,45,30
2,2026-03-25 18:15:20,2026,3,March,25,2,Wednesday,18,15,20
3,2026-04-10 21:00:10,2026,4,April,10,4,Friday,21,0,10
4,2026-05-05 10:20:55,2026,5,May,5,1,Tuesday,10,20,55