# Date Differences

Date Difference Feature Engineering is the process of calculating the time difference between two dates or timestamps.

Date differences can be represented as:

- Days
- Weeks
- Months
- Hours
- Minutes
- Seconds

These features are useful for measuring durations such as:

- Delivery time
- Customer membership duration
- Days since last purchase
- Subscription duration
- Time between events

In [1]:
import pandas as pd

df = pd.DataFrame({
    "Order_Date": [
        "2026-01-01",
        "2026-02-10",
        "2026-03-15",
        "2026-04-20"
    ],
    
    "Delivery_Date": [
        "2026-01-05",
        "2026-02-15",
        "2026-03-20",
        "2026-04-25"
    ]
})

df

   Order_Date Delivery_Date
0  2026-01-01    2026-01-05
1  2026-02-10    2026-02-15
2  2026-03-15    2026-03-20
3  2026-04-20    2026-04-25

## Converting Columns to Datetime

Before calculating date differences, both columns should be converted to Pandas datetime format.

We use:

`pd.to_datetime()`

In [2]:
df["Order_Date"] = pd.to_datetime(df["Order_Date"])
df["Delivery_Date"] = pd.to_datetime(df["Delivery_Date"])

df.dtypes

Order_Date       datetime64[us]
Delivery_Date    datetime64[us]
dtype: object

## Calculating Date Difference

We can subtract one datetime column from another.

Formula:

Date Difference = End Date - Start Date

The result is a Pandas Timedelta object.

In [3]:
df["Delivery_Time"] = (
    df["Delivery_Date"] - df["Order_Date"]
)

df

  Order_Date Delivery_Date Delivery_Time
0 2026-01-01    2026-01-05        4 days
1 2026-02-10    2026-02-15        5 days
2 2026-03-15    2026-03-20        5 days
3 2026-04-20    2026-04-25        5 days

In [4]:
df["Delivery_Days"] = (
    df["Delivery_Time"].dt.days
)

df

  Order_Date Delivery_Date Delivery_Time  Delivery_Days
0 2026-01-01    2026-01-05        4 days              4
1 2026-02-10    2026-02-15        5 days              5
2 2026-03-15    2026-03-20        5 days              5
3 2026-04-20    2026-04-25        5 days              5

## Difference in Hours

We can calculate the difference in hours using:

`dt.total_seconds() / 3600`

This is useful when the difference contains hours and minutes.

In [5]:
df["Delivery_Hours"] = (
    df["Delivery_Time"].dt.total_seconds() / 3600
)

df

  Order_Date Delivery_Date Delivery_Time  Delivery_Days  Delivery_Hours
0 2026-01-01    2026-01-05        4 days              4            96.0
1 2026-02-10    2026-02-15        5 days              5           120.0
2 2026-03-15    2026-03-20        5 days              5           120.0
3 2026-04-20    2026-04-25        5 days              5           120.0

In [6]:
df["Delivery_Minutes"] = (
    df["Delivery_Time"].dt.total_seconds() / 60
)

df

,Order_Date,Delivery_Date,Delivery_Time,Delivery_Days,Delivery_Hours,Delivery_Minutes
0,2026-01-01,2026-01-05,4 days,4,96.0,5760.0
1,2026-02-10,2026-02-15,5 days,5,120.0,7200.0
2,2026-03-15,2026-03-20,5 days,5,120.0,7200.0
3,2026-04-20,2026-04-25,5 days,5,120.0,7200.0

In [7]:
df["Delivery_Seconds"] = (
    df["Delivery_Time"].dt.total_seconds()
)

df

,Order_Date,Delivery_Date,Delivery_Time,Delivery_Days,Delivery_Hours,Delivery_Minutes,Delivery_Seconds
0,2026-01-01,2026-01-05,4 days,4,96.0,5760.0,345600.0
1,2026-02-10,2026-02-15,5 days,5,120.0,7200.0,432000.0
2,2026-03-15,2026-03-20,5 days,5,120.0,7200.0,432000.0
3,2026-04-20,2026-04-25,5 days,5,120.0,7200.0,432000.0

In [8]:
df["Delivery_Weeks"] = (
    df["Delivery_Days"] / 7
)

df

,Order_Date,Delivery_Date,Delivery_Time,Delivery_Days,Delivery_Hours,Delivery_Minutes,Delivery_Seconds,Delivery_Weeks
0,2026-01-01,2026-01-05,4 days,4,96.0,5760.0,345600.0,0.571429
1,2026-02-10,2026-02-15,5 days,5,120.0,7200.0,432000.0,0.714286
2,2026-03-15,2026-03-20,5 days,5,120.0,7200.0,432000.0,0.714286
3,2026-04-20,2026-04-25,5 days,5,120.0,7200.0,432000.0,0.714286

## Time Between Events

Date differences are useful for calculating the time between two events.

Examples:

- Order → Delivery
- Signup → First Purchase
- Login → Logout
- Start Date → End Date
- Purchase → Next Purchase

In [9]:
df_events = pd.DataFrame({
    "Signup_Date": pd.to_datetime([
        "2026-01-01",
        "2026-02-01",
        "2026-03-01"
    ]),
    
    "First_Purchase": pd.to_datetime([
        "2026-01-10",
        "2026-02-15",
        "2026-03-20"
    ])
})

df_events["Days_To_First_Purchase"] = (
    df_events["First_Purchase"]
    - df_events["Signup_Date"]
).dt.days

df_events

  Signup_Date First_Purchase  Days_To_First_Purchase
0  2026-01-01     2026-01-10                       9
1  2026-02-01     2026-02-15                      14
2  2026-03-01     2026-03-20                      19

## Days Since Last Purchase

A very common feature in customer analytics is:

Days Since Last Purchase

Formula:

Current Date - Last Purchase Date

This can help identify:

- Active customers
- Inactive customers
- Returning customers
- Customer churn

In [10]:
today = pd.Timestamp("2026-08-18")

df_customer = pd.DataFrame({
    "Last_Purchase": pd.to_datetime([
        "2026-08-15",
        "2026-08-01",
        "2026-07-01",
        "2026-06-01"
    ])
})

df_customer["Days_Since_Last_Purchase"] = (
    today - df_customer["Last_Purchase"]
).dt.days

df_customer

  Last_Purchase  Days_Since_Last_Purchase
0    2026-08-15                         3
1    2026-08-01                        17
2    2026-07-01                        48
3    2026-06-01                        78

In [11]:
df_subscription = pd.DataFrame({
    "Start_Date": pd.to_datetime([
        "2026-01-01",
        "2026-02-15",
        "2026-03-10"
    ]),
    
    "End_Date": pd.to_datetime([
        "2026-06-01",
        "2026-07-15",
        "2026-08-10"
    ])
})

df_subscription["Subscription_Days"] = (
    df_subscription["End_Date"]
    - df_subscription["Start_Date"]
).dt.days

df_subscription

  Start_Date   End_Date  Subscription_Days
0 2026-01-01 2026-06-01                151
1 2026-02-15 2026-07-15                150
2 2026-03-10 2026-08-10                153

## Handling Negative Date Differences

A negative difference usually means that the end date occurs before the start date.

For example:

Start Date → 2026-05-10

End Date → 2026-05-05

Difference → -5 days

Negative differences may indicate:

- Incorrect data
- Reversed dates
- Data entry errors
- A legitimate situation depending on the problem

Always investigate negative durations rather than blindly removing them.

In [12]:
df["Delivery_Days"].min()

np.int64(4)

In [13]:
invalid_dates = df[
    df["Delivery_Date"] < df["Order_Date"]
]

invalid_dates

Empty DataFrame
Columns: [Order_Date, Delivery_Date, Delivery_Time, Delivery_Days, Delivery_Hours, Delivery_Minutes, Delivery_Seconds, Delivery_Weeks]
Index: []