#  Correlation Matrix

Correlation measures the relationship between numerical variables.

The correlation value ranges from:

- **+1** → Perfect positive correlation
- **0** → No correlation
- **-1** → Perfect negative correlation

Correlation matrix helps us:

- Understand relationships between variables.
- Find important features.
- Detect highly correlated features.
- Perform feature selection before Machine Learning.

In [1]:
# Import Libraries
import seaborn as sns
import matplotlib.pyplot as plt
# Load Tips Dataset
tips = sns.load_dataset("tips")
# Display Dataset
tips.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [2]:
# Select only numerical columns
numeric_tips = tips.select_dtypes(include="number")
numeric_tips.head()

   total_bill   tip  size
0       16.99  1.01     2
1       10.34  1.66     3
2       21.01  3.50     3
3       23.68  3.31     2
4       24.59  3.61     4

In [3]:
# Calculate correlation matrix
correlation_matrix = numeric_tips.corr()
correlation_matrix

            total_bill       tip      size
total_bill    1.000000  0.675734  0.598315
tip           0.675734  1.000000  0.489299
size          0.598315  0.489299  1.000000