# Ordinal Encoding

Ordinal Encoding converts categorical features into numerical values while preserving the meaningful order between categories.

Ordinal features have a natural ranking.

Examples:

- Small < Medium < Large
- Low < Medium < High
- Beginner < Intermediate < Advanced
- Bachelor's < Master's < PhD

For example:

Small → 0
Medium → 1
Large → 2

The numerical values represent the order of the categories.

In [1]:
import pandas as pd

df = pd.DataFrame({
    "Size": [
        "Small",
        "Medium",
        "Large",
        "Medium",
        "Small",
        "Large"
    ]
})

df

     Size
0   Small
1  Medium
2   Large
3  Medium
4   Small
5   Large

In [2]:
df["Size"].unique()

<ArrowStringArray>
['Small', 'Medium', 'Large']
Length: 3, dtype: str

#### Manual Ordinal Encoding

We can manually define a mapping when we know the correct order of the categories.

For the Size feature:

Small → 0
Medium → 1
Large → 2

This approach gives us complete control over the ordering.

In [3]:
size_mapping = {
    "Small": 0,
    "Medium": 1,
    "Large": 2
}

df["Size_Encoded"] = df["Size"].map(size_mapping)

df

     Size  Size_Encoded
0   Small             0
1  Medium             1
2   Large             2
3  Medium             1
4   Small             0
5   Large             2

In [4]:
df[["Size", "Size_Encoded"]]

     Size  Size_Encoded
0   Small             0
1  Medium             1
2   Large             2
3  Medium             1
4   Small             0
5   Large             2

#### Education Level Example

Education level is an ordinal feature because the categories have a meaningful order.

For example:

High School < Bachelor's < Master's < PhD

In [5]:
education_df = pd.DataFrame({
    "Education": [
        "High School",
        "Bachelor's",
        "Master's",
        "PhD",
        "Bachelor's"
    ]
})

education_df

     Education
0  High School
1   Bachelor's
2     Master's
3          PhD
4   Bachelor's

In [6]:
education_mapping = {
    "High School": 0,
    "Bachelor's": 1,
    "Master's": 2,
    "PhD": 3
}

education_df["Education_Encoded"] = (
    education_df["Education"].map(education_mapping)
)

education_df

     Education  Education_Encoded
0  High School                  0
1   Bachelor's                  1
2     Master's                  2
3          PhD                  3
4   Bachelor's                  1

In [7]:
from sklearn.preprocessing import OrdinalEncoder

In [8]:
encoder = OrdinalEncoder(
    categories=[["Small", "Medium", "Large"]]
)

df["Size_Ordinal"] = encoder.fit_transform(
    df[["Size"]]
)

df

     Size  Size_Encoded  Size_Ordinal
0   Small             0           0.0
1  Medium             1           1.0
2   Large             2           2.0
3  Medium             1           1.0
4   Small             0           0.0
5   Large             2           2.0

In [9]:
df = pd.DataFrame({
    "Size": ["Small", "Medium", "Large", "Medium"],
    "Satisfaction": ["Low", "High", "Medium", "High"]
})

df

     Size Satisfaction
0   Small          Low
1  Medium         High
2   Large       Medium
3  Medium         High

In [10]:
encoder = OrdinalEncoder(
    categories=[
        ["Small", "Medium", "Large"],
        ["Low", "Medium", "High"]
    ]
)

encoded = encoder.fit_transform(df)

encoded_df = pd.DataFrame(
    encoded,
    columns=["Size_Encoded", "Satisfaction_Encoded"]
)

encoded_df

   Size_Encoded  Satisfaction_Encoded
0           0.0                   0.0
1           1.0                   2.0
2           2.0                   1.0
3           1.0                   2.0

In [11]:
result = pd.concat(
    [df, encoded_df],
    axis=1
)

result

     Size Satisfaction  Size_Encoded  Satisfaction_Encoded
0   Small          Low           0.0                   0.0
1  Medium         High           1.0                   2.0
2   Large       Medium           2.0                   1.0
3  Medium         High           1.0                   2.0