# Ordinal Encoding

Ordinal Encoding converts categorical features into numerical values while preserving the meaningful order between categories.

Ordinal features have a natural ranking.

Examples:

- Small < Medium < Large
- Low < Medium < High
- Beginner < Intermediate < Advanced
- Bachelor's < Master's < PhD

For example:

Small → 0
Medium → 1
Large → 2

The numerical values represent the order of the categories.

In [1]:
import pandas as pd

df = pd.DataFrame({
    "Size": [
        "Small",
        "Medium",
        "Large",
        "Medium",
        "Small",
        "Large"
    ]
})

df

     Size
0   Small
1  Medium
2   Large
3  Medium
4   Small
5   Large

In [2]:
df["Size"].unique()

<ArrowStringArray>
['Small', 'Medium', 'Large']
Length: 3, dtype: str

#### Manual Ordinal Encoding

We can manually define a mapping when we know the correct order of the categories.

For the Size feature:

Small → 0
Medium → 1
Large → 2

This approach gives us complete control over the ordering.

In [3]:
size_mapping = {
    "Small": 0,
    "Medium": 1,
    "Large": 2
}

df["Size_Encoded"] = df["Size"].map(size_mapping)

df

     Size  Size_Encoded
0   Small             0
1  Medium             1
2   Large             2
3  Medium             1
4   Small             0
5   Large             2

#### Using Scikit-Learn OrdinalEncoder

Scikit-learn provides `OrdinalEncoder` for encoding categorical input features.

We can explicitly specify the order of the categories so that the encoding represents the correct ranking.

In [4]:
from sklearn.preprocessing import OrdinalEncoder

In [5]:
encoder = OrdinalEncoder(
    categories=[["Small", "Medium", "Large"]]
)

df["Size_Ordinal"] = encoder.fit_transform(
    df[["Size"]]
)

df

     Size  Size_Encoded  Size_Ordinal
0   Small             0           0.0
1  Medium             1           1.0
2   Large             2           2.0
3  Medium             1           1.0
4   Small             0           0.0
5   Large             2           2.0

In [6]:
df = pd.DataFrame({
    "Size": ["Small", "Medium", "Large", "Medium"],
    "Satisfaction": ["Low", "High", "Medium", "High"]
})

df

     Size Satisfaction
0   Small          Low
1  Medium         High
2   Large       Medium
3  Medium         High

In [7]:
encoder = OrdinalEncoder(
    categories=[
        ["Small", "Medium", "Large"],
        ["Low", "Medium", "High"]
    ]
)

encoded = encoder.fit_transform(df)

encoded_df = pd.DataFrame(
    encoded,
    columns=["Size_Encoded", "Satisfaction_Encoded"]
)

encoded_df

   Size_Encoded  Satisfaction_Encoded
0           0.0                   0.0
1           1.0                   2.0
2           2.0                   1.0
3           1.0                   2.0

In [8]:
result = pd.concat(
    [df, encoded_df],
    axis=1
)

result

     Size Satisfaction  Size_Encoded  Satisfaction_Encoded
0   Small          Low           0.0                   0.0
1  Medium         High           1.0                   2.0
2   Large       Medium           2.0                   1.0
3  Medium         High           1.0                   2.0