# Frequency Encoding

Frequency Encoding is a categorical encoding technique that replaces each category with the number of times it appears in the dataset.

For example:

Lahore → 3
Karachi → 2
Islamabad → 1

Frequency Encoding converts categorical values into numerical values based on their frequency.

It is especially useful for categorical features with many unique categories.

In [1]:
import pandas as pd

df = pd.DataFrame({
    "City": [
        "Lahore",
        "Karachi",
        "Lahore",
        "Islamabad",
        "Karachi",
        "Lahore",
        "Lahore",
        "Islamabad"
    ]
})

df

        City
0     Lahore
1    Karachi
2     Lahore
3  Islamabad
4    Karachi
5     Lahore
6     Lahore
7  Islamabad

#### Calculating Category Frequency

First, we count how many times each category appears.

Pandas provides the `value_counts()` method for this purpose.

In [2]:
frequency = df["City"].value_counts()

frequency

City
Lahore       4
Karachi      2
Islamabad    2
Name: count, dtype: int64

#### Applying Frequency Encoding

We can replace each category with its corresponding frequency.

For example:

Lahore → 4
Karachi → 2
Islamabad → 2

Every occurrence of the same category receives the same numerical value.

In [3]:
df["City_Frequency"] = df["City"].map(frequency)

df

        City  City_Frequency
0     Lahore               4
1    Karachi               2
2     Lahore               4
3  Islamabad               2
4    Karachi               2
5     Lahore               4
6     Lahore               4
7  Islamabad               2

#### Frequency as a Percentage

Instead of using the raw count, we can represent frequency as a proportion of the total observations.

Formula:

Frequency Ratio = Category Count / Total Number of Observations

In [4]:
frequency_ratio = df["City"].value_counts(normalize=True)

frequency_ratio

City
Lahore       0.50
Karachi      0.25
Islamabad    0.25
Name: proportion, dtype: float64

In [5]:
df["City_Frequency_Ratio"] = df["City"].map(
    frequency_ratio
)

df

        City  City_Frequency  City_Frequency_Ratio
0     Lahore               4                  0.50
1    Karachi               2                  0.25
2     Lahore               4                  0.50
3  Islamabad               2                  0.25
4    Karachi               2                  0.25
5     Lahore               4                  0.50
6     Lahore               4                  0.50
7  Islamabad               2                  0.25

In [6]:
df[[
    "City",
    "City_Frequency",
    "City_Frequency_Ratio"
]]

        City  City_Frequency  City_Frequency_Ratio
0     Lahore               4                  0.50
1    Karachi               2                  0.25
2     Lahore               4                  0.50
3  Islamabad               2                  0.25
4    Karachi               2                  0.25
5     Lahore               4                  0.50
6     Lahore               4                  0.50
7  Islamabad               2                  0.25

#### Creating a Reusable Function

We can create a function to perform frequency encoding on any categorical column.

In [7]:
def frequency_encode(data, column):
    frequency = data[column].value_counts()
    
    data[column + "_Frequency"] = (
        data[column].map(frequency)
    )
    
    return data

In [8]:
df = pd.DataFrame({
    "City": [
        "Lahore",
        "Karachi",
        "Lahore",
        "Islamabad",
        "Karachi",
        "Lahore"
    ]
})

df = frequency_encode(df, "City")

df

        City  City_Frequency
0     Lahore               3
1    Karachi               2
2     Lahore               3
3  Islamabad               1
4    Karachi               2
5     Lahore               3

#### Frequency Encoding Multiple Features

Frequency Encoding can also be applied to multiple categorical features.

For example:

- City
- Department
- Product Category

In [9]:
df = pd.DataFrame({
    "City": [
        "Lahore", "Karachi", "Lahore",
        "Islamabad", "Karachi", "Lahore"
    ],
    "Department": [
        "IT", "HR", "IT",
        "Finance", "HR", "IT"
    ]
})

df

        City Department
0     Lahore         IT
1    Karachi         HR
2     Lahore         IT
3  Islamabad    Finance
4    Karachi         HR
5     Lahore         IT

In [10]:
for column in ["City", "Department"]:
    
    frequency = df[column].value_counts()
    
    df[column + "_Frequency"] = (
        df[column].map(frequency)
    )

df

        City Department  City_Frequency  Department_Frequency
0     Lahore         IT               3                     3
1    Karachi         HR               2                     2
2     Lahore         IT               3                     3
3  Islamabad    Finance               1                     1
4    Karachi         HR               2                     2
5     Lahore         IT               3                     3

#### High-Cardinality Features

Frequency Encoding is useful when a categorical feature has many unique categories.

For example:

- ZIP Code
- Product ID
- Customer ID
- Store ID
- Website Domain

One-Hot Encoding could create hundreds or thousands of columns.

Frequency Encoding represents each category using only one numerical feature.

In [11]:
df = pd.DataFrame({
    "Product": [
        "A", "A", "A",
        "B", "B",
        "C",
        "D", "D", "D", "D"
    ]
})

frequency = df["Product"].value_counts()

df["Product_Frequency"] = df["Product"].map(
    frequency
)

df

  Product  Product_Frequency
0       A                  3
1       A                  3
2       A                  3
3       B                  2
4       B                  2
5       C                  1
6       D                  4
7       D                  4
8       D                  4
9       D                  4