# Standardization

Standardization is a feature scaling technique that transforms numerical features so that they have:

- Mean ≈ 0
- Standard Deviation ≈ 1

It is also known as **Z-score normalization**.

The formula is:

z = (x - μ) / σ

Where:

- x = Original value
- μ = Mean of the feature
- σ = Standard deviation

Standardization does not force values into a fixed range such as 0 to 1.

## Why Do We Need Standardization?

Consider two features:

Age:
20, 25, 30, 35, 40

Salary:
25000, 40000, 60000, 90000, 150000

Salary has a much larger numerical scale than Age.

Algorithms that depend on distance, magnitude, or gradients may be affected by these different scales.

Standardization transforms the features to a comparable scale.

In [1]:
import pandas as pd

df = pd.DataFrame({
    "Age": [20, 25, 30, 35, 40],
    "Salary": [25000, 40000, 60000, 90000, 150000],
    "Experience": [1, 3, 5, 8, 12]
})

df

   Age  Salary  Experience
0   20   25000           1
1   25   40000           3
2   30   60000           5
3   35   90000           8
4   40  150000          12

In [2]:
df.describe()

             Age        Salary  Experience
count   5.000000       5.00000     5.00000
mean   30.000000   73000.00000     5.80000
std     7.905694   49446.94126     4.32435
min    20.000000   25000.00000     1.00000
25%    25.000000   40000.00000     3.00000
50%    30.000000   60000.00000     5.00000
75%    35.000000   90000.00000     8.00000
max    40.000000  150000.00000    12.00000

## Manual Standardization

We can standardize a feature using the Z-score formula:

z = (x - μ) / σ

Steps:

1. Calculate the mean.
2. Calculate the standard deviation.
3. Subtract the mean from each value.
4. Divide by the standard deviation.

In [3]:
mean = df["Age"].mean()
std = df["Age"].std()

df["Age_Standardized"] = (
    (df["Age"] - mean) / std
)

df

   Age  Salary  Experience  Age_Standardized
0   20   25000           1         -1.264911
1   25   40000           3         -0.632456
2   30   60000           5          0.000000
3   35   90000           8          0.632456
4   40  150000          12          1.264911

In [4]:
print("Mean:", df["Age_Standardized"].mean())
print("Standard Deviation:", df["Age_Standardized"].std())

Mean: 4.4408920985006264e-17
Standard Deviation: 1.0

## Standardizing Multiple Features

In a real machine learning project, we usually standardize multiple numerical features at the same time.

Scikit-learn provides `StandardScaler` for this purpose.

In [5]:
from sklearn.preprocessing import StandardScaler

In [6]:
features = [
    "Age",
    "Salary",
    "Experience"
]

scaler = StandardScaler()

df_scaled = pd.DataFrame(
    scaler.fit_transform(df[features]),
    columns=features
)

df_scaled

        Age    Salary  Experience
0 -1.414214 -1.085318   -1.241010
1 -0.707107 -0.746156   -0.723923
2  0.000000 -0.293940   -0.206835
3  0.707107  0.384383    0.568796
4  1.414214  1.741030    1.602972

In [7]:
print("Means:")
print(df_scaled.mean())

print("\nStandard Deviations:")
print(df_scaled.std())

Means:
Age           0.0
Salary        0.0
Experience    0.0
dtype: float64

Standard Deviations:
Age           1.118034
Salary        1.118034
Experience    1.118034
dtype: float64

In [8]:
print(df_scaled.mean())
print(df_scaled.std(ddof=0))

Age           0.0
Salary        0.0
Experience    0.0
dtype: float64
Age           1.0
Salary        1.0
Experience    1.0
dtype: float64

## Before vs After Standardization

Before standardization:

- Features have different numerical ranges.
- Salary has much larger values than Age.

After standardization:

- Features are centered around zero.
- Features have comparable scales.

In [9]:
print("Original Data:")
display(df[features])

print("\nStandardized Data:")
display(df_scaled)

Original Data:

   Age  Salary  Experience
0   20   25000           1
1   25   40000           3
2   30   60000           5
3   35   90000           8
4   40  150000          12

Standardized Data:

        Age    Salary  Experience
0 -1.414214 -1.085318   -1.241010
1 -0.707107 -0.746156   -0.723923
2  0.000000 -0.293940   -0.206835
3  0.707107  0.384383    0.568796
4  1.414214  1.741030    1.602972