# Max Absolute Scaling

Max Absolute Scaling is a feature scaling technique that scales each numerical feature according to its maximum absolute value.

The formula is:

x_scaled = x / max(|x|)

After scaling, the values generally fall within the range:

-1 to 1

Unlike Standardization, Max Absolute Scaling does not center the data around zero.

It is particularly useful for sparse datasets because it preserves zero values.

## Why Do We Need Max Absolute Scaling?

Different numerical features can have very different scales.

For example:

Age → 18 to 80
Salary → 20,000 to 500,000

A model that is sensitive to feature magnitude can be affected by these differences.

Max Absolute Scaling brings features to a comparable scale without shifting their zero values.

In [1]:
import pandas as pd

df = pd.DataFrame({
    "Age": [20, 25, 30, 35, 40],
    "Salary": [25000, 40000, 60000, 90000, 150000],
    "Experience": [1, 3, 5, 8, 12]
})

df

   Age  Salary  Experience
0   20   25000           1
1   25   40000           3
2   30   60000           5
3   35   90000           8
4   40  150000          12

## Maximum Absolute Value

For every feature, we find the maximum absolute value.

For example:

Age:

max(|20|, |25|, |30|, |35|, |40|) = 40

Salary:

max(|25000|, |40000|, |60000|, |90000|, |150000|) = 150000

Each value is then divided by its feature's maximum absolute value.

In [2]:
max_absolute = df.abs().max()

max_absolute

Age               40
Salary        150000
Experience        12
dtype: int64

## Manual Max Absolute Scaling

The formula is:

x_scaled = x / max(|x|)

For example:

Age = 30
Maximum Absolute Age = 40

30 / 40 = 0.75

Therefore:

30 → 0.75

In [3]:
df_manual = df.copy()

for column in df.columns:
    max_abs = df[column].abs().max()
    
    df_manual[column] = (
        df[column] / max_abs
    )

df_manual

     Age    Salary  Experience
0  0.500  0.166667    0.083333
1  0.625  0.266667    0.250000
2  0.750  0.400000    0.416667
3  0.875  0.600000    0.666667
4  1.000  1.000000    1.000000

## Using Scikit-Learn

Scikit-learn provides `MaxAbsScaler` for performing Max Absolute Scaling.

It scales each feature according to its maximum absolute value.

In [4]:
from sklearn.preprocessing import MaxAbsScaler

In [5]:
scaler = MaxAbsScaler()

df_scaled = pd.DataFrame(
    scaler.fit_transform(df),
    columns=df.columns
)

df_scaled

     Age    Salary  Experience
0  0.500  0.166667    0.083333
1  0.625  0.266667    0.250000
2  0.750  0.400000    0.416667
3  0.875  0.600000    0.666667
4  1.000  1.000000    1.000000

In [6]:
print("Maximum absolute values after scaling:")

print(df_scaled.abs().max())

Maximum absolute values after scaling:
Age           1.0
Salary        1.0
Experience    1.0
dtype: float64

## Handling Negative Values

Max Absolute Scaling preserves the sign of the original values.

For example:

-100 → -1.0
-50 → -0.5
0 → 0
50 → 0.5
100 → 1.0

Therefore, negative values remain negative and positive values remain positive.

In [7]:
df_negative = pd.DataFrame({
    "Feature": [-100, -50, -25, 0, 25, 50, 100]
})

scaler = MaxAbsScaler()

df_negative["Scaled"] = scaler.fit_transform(
    df_negative[["Feature"]]
)

df_negative

   Feature  Scaled
0     -100   -1.00
1      -50   -0.50
2      -25   -0.25
3        0    0.00
4       25    0.25
5       50    0.50
6      100    1.00

## Important Property: Zero Values Are Preserved

One major advantage of Max Absolute Scaling is that it does not shift the data.

If:

x = 0

then:

x_scaled = 0

This makes Max Absolute Scaling particularly useful for sparse datasets where many values are zero.

In [8]:
from scipy.sparse import csr_matrix

sparse_data = csr_matrix([
    [0, 100, 0],
    [50, 0, 200],
    [0, 0, 300]
])

sparse_data

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 4 stored elements and shape (3, 3)>

In [9]:
scaler = MaxAbsScaler()

scaled_sparse = scaler.fit_transform(
    sparse_data
)

scaled_sparse

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 4 stored elements and shape (3, 3)>

In [10]:
print("Original Data:")
display(df)

print("\nMax Absolute Scaled Data:")
display(df_scaled)

Original Data:

   Age  Salary  Experience
0   20   25000           1
1   25   40000           3
2   30   60000           5
3   35   90000           8
4   40  150000          12

Max Absolute Scaled Data:

     Age    Salary  Experience
0  0.500  0.166667    0.083333
1  0.625  0.266667    0.250000
2  0.750  0.400000    0.416667
3  0.875  0.600000    0.666667
4  1.000  1.000000    1.000000