# Regression Metrics

Regression metrics are used to evaluate the performance of regression models.

Unlike classification, where we predict discrete classes, regression models predict continuous numerical values.

For example:

- House Price → 250000
- Salary → 85000
- Temperature → 32.5
- Sales → 15420.75

Regression metrics measure how close the predicted values are to the actual values.

### Common Regression Metrics

1. Mean Absolute Error (MAE)
2. Mean Squared Error (MSE)
3. Root Mean Squared Error (RMSE)
4. R² Score
5. Adjusted R² Score
6. Mean Absolute Percentage Error (MAPE)

We will use these metrics to compare regression models.

In [1]:
import numpy as np
import pandas as pd

# Actual values
y_actual = np.array([
    100,
    200,
    300,
    400,
    500
])

# Predicted values
y_pred = np.array([
    110,
    190,
    320,
    380,
    510
])

# Create DataFrame
comparison = pd.DataFrame({
    "Actual": y_actual,
    "Predicted": y_pred
})

comparison

   Actual  Predicted
0     100        110
1     200        190
2     300        320
3     400        380
4     500        510

## Residuals

A residual is the difference between the actual value and predicted value.

$$
Residual = y - \hat{y}
$$

A residual can be:

- Positive → Model underestimated
- Negative → Model overestimated
- Zero → Perfect prediction

In [2]:
# Calculate residuals

residuals = y_actual - y_pred

comparison["Residual"] = residuals

comparison

   Actual  Predicted  Residual
0     100        110       -10
1     200        190        10
2     300        320       -20
3     400        380        20
4     500        510       -10

# Mean Absolute Error (MAE)

**Mean Absolute Error (MAE)** calculates the average absolute difference between actual and predicted values.

$$
MAE =
\frac{1}{n}
\sum_{i=1}^{n}
|y_i - \hat{y}_i|
$$

Where:

- $y_i$ = Actual value
- $\hat{y}_i$ = Predicted value
- $n$ = Number of observations

### Interpretation

MAE tells us the average size of the prediction error.

For example:

```text
MAE = 10,000

In [3]:
from sklearn.metrics import mean_absolute_error

mae = mean_absolute_error(
    y_actual,
    y_pred
)

print("MAE:", mae)

MAE: 14.0

# Mean Squared Error (MSE)

**Mean Squared Error (MSE)** calculates the average squared difference between actual and predicted values.

$$
MSE =
\frac{1}{n}
\sum_{i=1}^{n}
(y_i - \hat{y}_i)^2
$$

The errors are squared before taking the average.

### Why Square the Errors?

Squaring:

- Makes all errors positive
- Penalizes large errors more heavily

For example:

```text
Error = 2
Squared Error = 4

Error = 10
Squared Error = 100

In [4]:
from sklearn.metrics import mean_squared_error

mse = mean_squared_error(
    y_actual,
    y_pred
)

print("MSE:", mse)

MSE: 220.0

# Root Mean Squared Error (RMSE)

**Root Mean Squared Error (RMSE)** is the square root of MSE.

$$
RMSE = \sqrt{MSE}
$$

Or:

$$
RMSE =
\sqrt{
\frac{1}{n}
\sum_{i=1}^{n}
(y_i - \hat{y}_i)^2
}
$$

RMSE is useful because it is expressed in the **same units as the target variable**.

### Example

If we are predicting house prices:

```text
RMSE = 15000

In [5]:
rmse = np.sqrt(
    mean_squared_error(
        y_actual,
        y_pred
    )
)

print("RMSE:", rmse)

RMSE: 14.832396974191326

# R² Score

**R² (R-squared)** measures how well the regression model explains the variation in the target variable.

It is also called the **coefficient of determination**.

$$
R^2 =
1 -
\frac{
\sum(y_i-\hat{y}_i)^2
}{
\sum(y_i-\bar{y})^2
}
$$

Where:

- $y_i$ = Actual value
- $\hat{y}_i$ = Predicted value
- $\bar{y}$ = Mean of actual values

### Interpretation

A higher R² generally indicates a better fit.

```text
R² = 1
→ Perfect prediction

R² = 0
→ Model performs roughly like predicting the mean

R² < 0
→ Model can perform worse than the mean baseline

In [6]:
from sklearn.metrics import r2_score

r2 = r2_score(
    y_actual,
    y_pred
)

print("R² Score:", r2)

R² Score: 0.989