# 📧 Spam Email Detection using Natural Language Processing (NLP)

## 📌 Project Overview

This project aims to build a Machine Learning model that automatically classifies emails as **Spam** or **Not Spam (Ham)**. The project uses Natural Language Processing (NLP) techniques to preprocess text, convert it into numerical features using the **Bag of Words (BoW)** method, train multiple classification models, compare their performance, and build a prediction pipeline for classifying new email messages.

---

## 🎯 Objectives

- Build an email spam detection system.
- Perform text preprocessing using NLP.
- Convert text into numerical features using Bag of Words.
- Train multiple Machine Learning models.
- Compare model performance.
- Select the best-performing model.
- Create a user prediction pipeline.

---

## 📂 Dataset

The dataset contains email messages and their corresponding labels.

- **Text** → Email content
- **Label** → Spam or Ham (Not Spam)

---

## 🛠 Technologies Used

- Python
- Pandas
- NumPy
- NLTK
- BeautifulSoup
- Scikit-learn
- Matplotlib
- Seaborn

---

## 🧹 Text Preprocessing

The following preprocessing steps were applied:

- Convert text to lowercase
- Remove HTML tags
- Remove URLs
- Remove punctuation
- Remove numbers
- Remove extra spaces
- Tokenization
- Remove stop words
- Lemmatization
- Join tokens into complete sentences

---

## 🔢 Feature Engineering

The cleaned text was transformed into numerical features using the **Bag of Words (CountVectorizer)** technique.

---

## 🤖 Machine Learning Models

The following models were trained and compared:

- Multinomial Naive Bayes
- Logistic Regression
- Support Vector Machine (SVM)

---

## 📊 Model Evaluation

The models were evaluated using:

- Accuracy

The model with the best performance was selected for the final prediction pipeline.

---

## 🚀 Prediction Pipeline

The final prediction pipeline performs the following steps:

1. Accepts an email from the user.
2. Applies the same preprocessing used during training.
3. Converts the email into Bag of Words features.
4. Predicts whether the email is **Spam** or **Not Spam (Ham)**.
5. Displays the prediction result.

---

## 📚 Skills Demonstrated

- Natural Language Processing (NLP)
- Text Preprocessing
- Feature Engineering
- Bag of Words
- Machine Learning
- Model Evaluation
- Prediction Pipeline Development

---

## 🏁 Conclusion

This project demonstrates a complete end-to-end NLP workflow for spam email classification. It includes text preprocessing, feature extraction using Bag of Words, training and comparing multiple Machine Learning models, selecting the best-performing model, and building a prediction pipeline for real-world email classification.

Importing Libraries

In [72]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from wordcloud import WordCloud
import re
import string
from bs4 import BeautifulSoup
from textblob import TextBlob
import nltk
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords
from nltk.stem import PorterStemmer
from nltk.stem import WordNetLemmatizer
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.model_selection import train_test_split
from gensim.models import Word2Vec
from sklearn.naive_bayes import MultinomialNB
from sklearn.svm import SVC
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import (
    accuracy_score,
)
import warnings
warnings.filterwarnings("ignore")

Load the dataset

In [73]:
data=pd.read_csv("D:\DATA_SCIENCE_PROJECTS\DATASETS\combined_data.csv")
data.head()

   label                                               text
0      1  ounce feather bowl hummingbird opec moment ala...
1      1  wulvob get your medircations online qnb ikud v...
2      0   computer connection from cnn com wednesday es...
3      1  university degree obtain a prosperous future m...
4      0  thanks for all your answers guys i know i shou...

Taking sample from the data

In [74]:
data=data.sample(n=10000)
data

       label                                               text
58363      0  friday may escapenumber escapenumber watch and...
6335       1  my first displays the wealth and pomp of kings...
54287      1  fw : be ordained now !\nbecome a\nlegally orda...
40171      0  do you and george have a thing going ?\n- - - ...
27560      1  prison and did not minister unto thee then sha...
...      ...                                                ...
67623      1  escapelong escapelong escapelong escapelong es...
61872      1  802 . 11 b / g wireless\nusb adapter\n$ 37 . 0...
75694      0  find attached the mc model for talon . a copy ...
29420      0  i am wondering if some of the lawyers legal st...
5666       1  hey jimmy it was really fun going out the othe...

[10000 rows x 2 columns]

In [75]:
data.shape

(10000, 2)

In [76]:
data.isnull().sum()

label    0
text     0
dtype: int64

In [77]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 10000 entries, 58363 to 5666
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   label   10000 non-null  int64
 1   text    10000 non-null  object
dtypes: int64(1), object(1)
memory usage: 234.4+ KB

In [78]:
data["label"].value_counts()

label
1    5144
0    4856
Name: count, dtype: int64

Data Preprocessing

In [79]:
data[~data["text"].str.islower()]

       label                                               text
65797      1  greetings ,\ni crave your indulgence as i cont...
31829      1  faturasiz\nÝetÝÞÝm\nuluslararasý telefon\ngörü...
29966      1  from : barrister samson ajayi malolo\nphilip a...
14115      1  faturasiz\nÝletÝÞÝm\nuluslararasý telefon\ngör...
31331      1  notebook hp compaqã? ¤ ? ¶ ù ¡ êø ´ æ Üí § ãëá...
69541      1  sex ohne finanziellem interesse !\nÜberall gib...
25120      0                                       70422\n92754

In [80]:
#convering the data into lowe case
data.text=data.text.str.lower()
data.head()

       label                                               text
58363      0  friday may escapenumber escapenumber watch and...
6335       1  my first displays the wealth and pomp of kings...
54287      1  fw : be ordained now !\nbecome a\nlegally orda...
40171      0  do you and george have a thing going ?\n- - - ...
27560      1  prison and did not minister unto thee then sha...

In [81]:
#removes the html tages
data.text=data.text.apply(lambda x: BeautifulSoup(x, 'html.parser').get_text())
data.head()

       label                                               text
58363      0  friday may escapenumber escapenumber watch and...
6335       1  my first displays the wealth and pomp of kings...
54287      1  fw : be ordained now !\nbecome a\nlegally orda...
40171      0  do you and george have a thing going ?\n- - - ...
27560      1  prison and did not minister unto thee then sha...

In [82]:
#removes the numbers
data.text=data.text.apply(lambda x: re.sub(r'\d+', '', x))
data.head()

       label                                               text
58363      0  friday may escapenumber escapenumber watch and...
6335       1  my first displays the wealth and pomp of kings...
54287      1  fw : be ordained now !\nbecome a\nlegally orda...
40171      0  do you and george have a thing going ?\n- - - ...
27560      1  prison and did not minister unto thee then sha...

In [83]:
#removes the punctuations
data.text=data.text.apply(lambda x: x.translate(str.maketrans('', '', string.punctuation)))
data.head()

       label                                               text
58363      0  friday may escapenumber escapenumber watch and...
6335       1  my first displays the wealth and pomp of kings...
54287      1  fw  be ordained now \nbecome a\nlegally ordain...
40171      0  do you and george have a thing going \n       ...
27560      1  prison and did not minister unto thee then sha...

In [84]:
#removes the urls
data.text=data.text.apply(lambda x: re.sub(r'http\S+', '', x))
data.head()

       label                                               text
58363      0  friday may escapenumber escapenumber watch and...
6335       1  my first displays the wealth and pomp of kings...
54287      1  fw  be ordained now \nbecome a\nlegally ordain...
40171      0  do you and george have a thing going \n       ...
27560      1  prison and did not minister unto thee then sha...

In [85]:
#removes the extra spaces
data.text=data.text.apply(lambda x: " ".join(x.split()))
data.head()

       label                                               text
58363      0  friday may escapenumber escapenumber watch and...
6335       1  my first displays the wealth and pomp of kings...
54287      1  fw be ordained now become a legally ordained m...
40171      0  do you and george have a thing going sent from...
27560      1  prison and did not minister unto thee then sha...

In [86]:
#cehcking for the urls
url_rows = data[data['text'].str.contains(r'http\S+|www\S+', regex=True, na=False)]
url_rows

       label                                               text
21339      1  treat yourself and your woman to a marvelous s...
50992      0  the tools do not include an fescapenumberx com...
77762      1  some cigarette ends had collected together in ...
19169      1  cd uptake dvd drives badly fea channel choices...
25125      1  our art team creates a custom logo for you bas...
52147      0  track manage your source code and digital asse...
17494      1  treat yourself and your woman to a marvelous s...
619        1  racing pc eminem and radio tuner boehmer guzel...
34464      1  tbody memo june escapenumbernd escapenumber co...
82311      1  thing happy rightclick deal switch modes talki...
31509      1  greetings have you ever thought the only thing...
60423      1  up escapenumber in escapenumber days http wwwe...
5950       1  you have just received a virtual postcard from...
39006      0  if you try rcmd install mypackage you will get...

In [87]:
#converting the text into tokens by using nltk library
from nltk.tokenize import word_tokenize
data["text"] = data["text"].apply(lambda x: word_tokenize(x))
data.head()

       label                                               text
58363      0  [friday, may, escapenumber, escapenumber, watc...
6335       1  [my, first, displays, the, wealth, and, pomp, ...
54287      1  [fw, be, ordained, now, become, a, legally, or...
40171      0  [do, you, and, george, have, a, thing, going, ...
27560      1  [prison, and, did, not, minister, unto, thee, ...

In [88]:
stop_words = set(stopwords.words("english"))
data["text"] = data["text"].apply(
    lambda words: [word for word in words if word.lower() not in stop_words]
)

data.head()

       label                                               text
58363      0  [friday, may, escapenumber, escapenumber, watc...
6335       1  [first, displays, wealth, pomp, kings, lords, ...
54287      1  [fw, ordained, become, legally, ordained, mini...
40171      0  [george, thing, going, sent, blackberry, wirel...
27560      1  [prison, minister, unto, thee, shall, answer, ...

In [89]:
lemmatizer = WordNetLemmatizer()
data["text"] = data["text"].apply(
    lambda words: [lemmatizer.lemmatize(word) for word in words]
)
data.head()

       label                                               text
58363      0  [friday, may, escapenumber, escapenumber, watc...
6335       1  [first, display, wealth, pomp, king, lord, ear...
54287      1  [fw, ordained, become, legally, ordained, mini...
40171      0  [george, thing, going, sent, blackberry, wirel...
27560      1  [prison, minister, unto, thee, shall, answer, ...

In [90]:
print(type(data["text"].iloc[0]))
print(data["text"].iloc[0])

<class 'list'>
['friday', 'may', 'escapenumber', 'escapenumber', 'watch', 'learn', 'report', 'new', 'immigration', 'bill', 'lead', 'last', 'broadcast', 'week', 'review', 'week', 'top', 'story', 'travel', 'new', 'york', 'city', 'official', 'around', 'globe', 'met', 'discus', 'climate', 'change', 'new', 'fla', 'law', 'requires', 'p', 'e', 'elementary', 'school', 'elementary', 'school', 'student', 'must', 'least', 'half', 'hour', 'physical', 'education', 'day', 'bill', 'signed', 'thursday', 'health', 'conscious', 'gov', 'charlie', 'crist', 'may', 'escapenumber', 'escapenumber', 'gradys', 'anatomy', 'warning', 'educator', 'please', 'preview', 'program', 'contains', 'content', 'might', 'inappropriate', 'student', 'gradys', 'anatomy', 'chronicle', 'challenge', 'pressure', 'faced', 'dr', 'sanjay', 'gupta', 'four', 'resident', 'grady', 'memorial', 'hospital', 'atlanta', 'georgia', 'care', 'patient', 'inner', 'city', 'hospital', 'juggle', 'escapenumber', 'hour', 'workweek', 'personal', 'life', 'record', 'commercial', 'free', 'cnn', 'classroom', 'edition', 'every', 'monday', 'escapenumber', 'escapenumber', 'escapenumber', 'escapenumber', 'et', 'educational', 'material', 'episode', 'available', 'cnn', 'com', 'education', 'please', 'note', 'cnn', 'classroom', 'edition', 'may', 'pre', 'empted', 'time', 'coverage', 'breaking', 'news', 'week', 'may', 'escapenumber', 'escapenumber', 'jamestown', 'virginia', 'escapenumber', 'saudi', 'arabia', 'escapenumber', 'jerry', 'falwell', 'escapenumber', 'subsidy', 'escapenumber', 'georgia', 'florida', 'escapenumber', 'prince', 'harry', 'escapenumber', 'al', 'anbar', 'escapenumber', 'new', 'york', 'escapenumber', 'armed', 'force', 'day', 'escapenumber', 'alaska', 'access', 'week', 'newsquiz', 'cnn', 'student', 'news', 'escapenumber', 'minute', 'commercial', 'free', 'news', 'program', 'air', 'cnn', 'headline', 'news', 'escapenumber', 'escapenumber', 'est', 'well', 'cnn', 'com', 'education', 'created', 'team', 'journalist', 'educator', 'program', 'provides', 'top', 'story', 'day', 'segment', 'encourage', 'student', 'participation', 'depth', 'special', 'report', 'addition', 'cnn', 'student', 'news', 'provides', 'free', 'curriculum', 'cnn', 'com', 'education', 'accompany', 'program', 'content', 'cnn', 'student', 'news', 'along', 'cnn', 'classroom', 'edition', 'turner', 'broadcasting', 'contribution', 'cable', 'classroom', 'forward', 'friend', 'received', 'email', 'signed', 'receive', 'cnn', 'student', 'news', 'newsletter', 'click', 'unsubscribe', 'edit', 'profile']

In [91]:
data["text"] = data["text"].apply(lambda x: " ".join(x))
data.head()

       label                                               text
58363      0  friday may escapenumber escapenumber watch lea...
6335       1  first display wealth pomp king lord earth th m...
54287      1  fw ordained become legally ordained minister w...
40171      0  george thing going sent blackberry wireless ha...
27560      1  prison minister unto thee shall answer escapen...

In [106]:
vectorizer = CountVectorizer()
X = vectorizer.fit_transform(data["text"])
X

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 910232 stored elements and shape (10000, 88952)>

In [107]:
y=data["label"] 
y

58363    0
6335     1
54287    1
40171    0
27560    1
        ..
67623    1
61872    1
75694    0
29420    0
5666     1
Name: label, Length: 10000, dtype: int64

In [108]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((8000, 88952), (2000, 88952), (8000,), (2000,))

In [110]:
naive_bayes = MultinomialNB()

svm = SVC()

logistic_regression = LogisticRegression(max_iter=1000)

In [111]:
naive_bayes.fit(X_train, y_train)

svm.fit(X_train, y_train)

logistic_regression.fit(X_train, y_train)

LogisticRegression(max_iter=1000)

In [112]:
nb_prediction = naive_bayes.predict(X_test)

svm_prediction = svm.predict(X_test)

lr_prediction = logistic_regression.predict(X_test)

In [114]:
nb_accuracy = accuracy_score(y_test, nb_prediction)

svm_accuracy = accuracy_score(y_test, svm_prediction)

lr_accuracy = accuracy_score(y_test, lr_prediction)
print("Naive Bayes Accuracy:", nb_accuracy)

print("SVM Accuracy:", svm_accuracy)

print("Logistic Regression Accuracy:", lr_accuracy)

Naive Bayes Accuracy: 0.966
SVM Accuracy: 0.894
Logistic Regression Accuracy: 0.969

In [115]:
results = {
    "Naive Bayes": nb_accuracy,
    "SVM": svm_accuracy,
    "Logistic Regression": lr_accuracy
}

for model, accuracy in results.items():
    print(f"{model}: {accuracy:.4f}")

Naive Bayes: 0.9660
SVM: 0.8940
Logistic Regression: 0.9690

In [116]:
best_model = max(results, key=results.get)

print("Best Model:", best_model)

print("Best Accuracy:", results[best_model])

Best Model: Logistic Regression
Best Accuracy: 0.969

In [133]:
def predict_email():

    # Take user input
    email = input("Enter your email message:\n")

    # 1. Lowercase
    email = email.lower()

    # 2. Remove HTML
    email = BeautifulSoup(email, "html.parser").get_text()

    # 3. Remove URLs
    email = re.sub(r'http\S+|www\S+', '', email)

    # 4. Remove punctuation
    email = email.translate(str.maketrans('', '', string.punctuation))

    # 5. Remove numbers
    email = re.sub(r'\d+', '', email)

    # 6. Remove extra spaces
    email = " ".join(email.split())

    # 7. Tokenization
    words = word_tokenize(email)

    # 8. Remove stop words
    words = [word for word in words if word not in stop_words]

    # 9. Lemmatization
    words = [lemmatizer.lemmatize(word) for word in words]

    # 10. Join words
    email = " ".join(words)

    # 11. Bag of Words
    email_vector = vectorizer.transform([email])

    # 12. Prediction
    prediction = logistic_regression.predict(email_vector)

    # 13. Probability
    probability = logistic_regression.predict_proba(email_vector)

    # 14. Result
    if prediction[0] == 1:
        print("\n🚨 Spam Email")
    else:
        print("\n✅ Not Spam (Ham)")

    print(f"Confidence: {max(probability[0]) * 100:.2f}%")
predict_email()

✅ Not Spam (Ham)
Confidence: 75.00%