#  Data Exploration with Pandas

Data Exploration is the process of understanding the structure, quality, and contents of a dataset before performing data cleaning, visualization, or machine learning.

#### Importing pandas in python

In [1]:
import pandas as pd

#### Load the data

In [3]:
df = pd.read_csv("students.csv")
df

   Student_ID    Name  Age Department  Marks        City
0         101     Ali   20         CS     85      Lahore
1         102   Ahmed   21         IT     90     Karachi
2         103    Sara   19         SE     78   Islamabad
3         104  Ayesha   22         AI     92    Peshawar
4         105   Usman   20         CS     88  Faisalabad

#### head()

The `head()` function displays the first rows of the dataset.

By default, it returns the first **5 rows**.

In [4]:
df.head()

   Student_ID    Name  Age Department  Marks        City
0         101     Ali   20         CS     85      Lahore
1         102   Ahmed   21         IT     90     Karachi
2         103    Sara   19         SE     78   Islamabad
3         104  Ayesha   22         AI     92    Peshawar
4         105   Usman   20         CS     88  Faisalabad

#### tail()

The `tail()` function displays the last rows of the dataset.

By default, it returns the last **5 rows**.

In [5]:
df.tail()

   Student_ID    Name  Age Department  Marks        City
0         101     Ali   20         CS     85      Lahore
1         102   Ahmed   21         IT     90     Karachi
2         103    Sara   19         SE     78   Islamabad
3         104  Ayesha   22         AI     92    Peshawar
4         105   Usman   20         CS     88  Faisalabad

#### sample()

The `sample()` function returns random rows from the dataset.

It is useful for quickly inspecting random records.

In [6]:
df.sample(3)

   Student_ID   Name  Age Department  Marks       City
0         101    Ali   20         CS     85     Lahore
2         103   Sara   19         SE     78  Islamabad
1         102  Ahmed   21         IT     90    Karachi

#### shape

Returns the number of rows and columns.

Format:

(rows, columns)

In [7]:
df.shape

(5, 6)

#### Columns names

In [8]:
df.columns

Index(['Student_ID', 'Name', 'Age', 'Department', 'Marks', 'City'], dtype='object')

#### dtypes

Displays the data type of each column.

In [9]:
df.dtypes

Student_ID     int64
Name          object
Age            int64
Department    object
Marks          int64
City          object
dtype: object

#### info()

Displays a summary of the dataset, including:

- Number of rows
- Number of columns
- Column names
- Data types
- Non-null values
- Memory usage

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Student_ID  5 non-null      int64
 1   Name        5 non-null      object
 2   Age         5 non-null      int64
 3   Department  5 non-null      object
 4   Marks       5 non-null      int64
 5   City        5 non-null      object
dtypes: int64(3), object(3)
memory usage: 372.0+ bytes

#### describe()

Generates statistical information for numerical columns.

In [12]:
df.describe()

       Student_ID        Age      Marks
count    5.000000   5.000000   5.000000
mean   103.000000  20.400000  86.600000
std      1.581139   1.140175   5.458938
min    101.000000  19.000000  78.000000
25%    102.000000  20.000000  85.000000
50%    103.000000  20.000000  88.000000
75%    104.000000  21.000000  90.000000
max    105.000000  22.000000  92.000000

In [11]:
df.describe(include="all")

        Student_ID Name        Age Department      Marks    City
count     5.000000    5   5.000000          5   5.000000       5
unique         NaN    5        NaN          4        NaN       5
top            NaN  Ali        NaN         CS        NaN  Lahore
freq           NaN    1        NaN          2        NaN       1
mean    103.000000  NaN  20.400000        NaN  86.600000     NaN
std       1.581139  NaN   1.140175        NaN   5.458938     NaN
min     101.000000  NaN  19.000000        NaN  78.000000     NaN
25%     102.000000  NaN  20.000000        NaN  85.000000     NaN
50%     103.000000  NaN  20.000000        NaN  88.000000     NaN
75%     104.000000  NaN  21.000000        NaN  90.000000     NaN
max     105.000000  NaN  22.000000        NaN  92.000000     NaN

#### value_counts()

Counts how many times each value appears in a column.

In [13]:
df["Department"].value_counts()

Department
CS    2
IT    1
SE    1
AI    1
Name: count, dtype: int64

In [14]:
df["Department"].value_counts(normalize=True)

Department
CS    0.4
IT    0.2
SE    0.2
AI    0.2
Name: proportion, dtype: float64

#### Unique values

In [15]:
df["Department"].unique()

array(['CS', 'IT', 'SE', 'AI'], dtype=object)

#### Number of unique values

In [16]:
df["Department"].nunique()

4

#### Missing values

In [17]:
df.isnull().sum()

Student_ID    0
Name          0
Age           0
Department    0
Marks         0
City          0
dtype: int64

In [19]:
df.isnull().any().sum()

np.int64(0)

#### Duplicated Rows

In [20]:
df.duplicated().sum()

np.int64(0)