# Selecting Data in Pandas

#### Importing pandas

In [32]:
import pandas as pd

#### Load the dataset

In [33]:
df = pd.read_csv("students.csv")
df

   Student_ID    Name  Age Department  Marks        City
0         101     Ali   20         CS     85      Lahore
1         102   Ahmed   21         IT     90     Karachi
2         103    Sara   19         SE     78   Islamabad
3         104  Ayesha   22         AI     92    Peshawar
4         105   Usman   20         CS     88  Faisalabad

#### Selecting One Column

A single column can be selected using its column name.

In [34]:
df["Name"]

0       Ali
1     Ahmed
2      Sara
3    Ayesha
4     Usman
Name: Name, dtype: object

#### Selecting Multiple Columns

Multiple columns can be selected using a list of column names.

In [35]:
df[["Name","Marks"]]

     Name  Marks
0     Ali     85
1   Ahmed     90
2    Sara     78
3  Ayesha     92
4   Usman     88

#### Selecting Single row

In [36]:
df.iloc[0]

Student_ID       101
Name             Ali
Age               20
Department        CS
Marks             85
City          Lahore
Name: 0, dtype: object

#### Selecting Multiple Row

In [37]:
df.iloc[0:3]

   Student_ID   Name  Age Department  Marks       City
0         101    Ali   20         CS     85     Lahore
1         102  Ahmed   21         IT     90    Karachi
2         103   Sara   19         SE     78  Islamabad

#### loc[]

`loc[]` selects data using row labels and column names.

In [38]:
df.loc[0,"Marks"]

np.int64(85)

In [39]:
df.loc[0:2,["Name","Marks"]]

    Name  Marks
0    Ali     85
1  Ahmed     90
2   Sara     78

#### iloc[]

`iloc[]` selects data using row and column positions.

In [40]:
df.iloc[0]

Student_ID       101
Name             Ali
Age               20
Department        CS
Marks             85
City          Lahore
Name: 0, dtype: object

In [41]:
df.iloc[0,4]

np.int64(85)

In [42]:
df.iloc[0:3,1:5]

    Name  Age Department  Marks
0    Ali   20         CS     85
1  Ahmed   21         IT     90
2   Sara   19         SE     78

#### Conditional Selection

In [43]:
df[df["Marks"]>85]

   Student_ID    Name  Age Department  Marks        City
1         102   Ahmed   21         IT     90     Karachi
3         104  Ayesha   22         AI     92    Peshawar
4         105   Usman   20         CS     88  Faisalabad

In [44]:
df[df["Department"]=="CS"]

   Student_ID   Name  Age Department  Marks        City
0         101    Ali   20         CS     85      Lahore
4         105  Usman   20         CS     88  Faisalabad

In [45]:
df[df["Age"]>20]

   Student_ID    Name  Age Department  Marks      City
1         102   Ahmed   21         IT     90   Karachi
3         104  Ayesha   22         AI     92  Peshawar