# Filtering Data in Pandas

#### Importing pandas

In [24]:
import pandas as pd

#### Load the dataset

In [25]:
df = pd.read_csv("students.csv")
df

   Student_ID    Name  Age Department  Marks        City
0         101     Ali   20         CS     85      Lahore
1         102   Ahmed   21         IT     90     Karachi
2         103    Sara   19         SE     78   Islamabad
3         104  Ayesha   22         AI     92    Peshawar
4         105   Usman   20         CS     88  Faisalabad

#### Comparison Operators

In [26]:
df[df["Marks"] > 85]

   Student_ID    Name  Age Department  Marks        City
1         102   Ahmed   21         IT     90     Karachi
3         104  Ayesha   22         AI     92    Peshawar
4         105   Usman   20         CS     88  Faisalabad

In [27]:
df[df["Marks"] < 90]

   Student_ID   Name  Age Department  Marks        City
0         101    Ali   20         CS     85      Lahore
2         103   Sara   19         SE     78   Islamabad
4         105  Usman   20         CS     88  Faisalabad

In [28]:
df[df["Marks"] == 90]

   Student_ID   Name  Age Department  Marks     City
1         102  Ahmed   21         IT     90  Karachi

In [29]:
df[df["Marks"] != 90]

   Student_ID    Name  Age Department  Marks        City
0         101     Ali   20         CS     85      Lahore
2         103    Sara   19         SE     78   Islamabad
3         104  Ayesha   22         AI     92    Peshawar
4         105   Usman   20         CS     88  Faisalabad

#### Logical Operators

In [30]:
df[(df["Marks"] > 80) & (df["Age"] >= 20)]

   Student_ID    Name  Age Department  Marks        City
0         101     Ali   20         CS     85      Lahore
1         102   Ahmed   21         IT     90     Karachi
3         104  Ayesha   22         AI     92    Peshawar
4         105   Usman   20         CS     88  Faisalabad

In [31]:
df[(df["Marks"] > 90) | (df["Age"] < 20)]

   Student_ID    Name  Age Department  Marks       City
2         103    Sara   19         SE     78  Islamabad
3         104  Ayesha   22         AI     92   Peshawar

In [32]:
df[~(df["Department"] == "CS")]

   Student_ID    Name  Age Department  Marks       City
1         102   Ahmed   21         IT     90    Karachi
2         103    Sara   19         SE     78  Islamabad
3         104  Ayesha   22         AI     92   Peshawar

#### Multiple Conditions

In [33]:
df[(df["Department"] == "CS") & (df["Marks"] > 85)]

   Student_ID   Name  Age Department  Marks        City
4         105  Usman   20         CS     88  Faisalabad

In [34]:
df[(df["Department"] == "AI") | (df["Department"] == "IT")]

   Student_ID    Name  Age Department  Marks      City
1         102   Ahmed   21         IT     90   Karachi
3         104  Ayesha   22         AI     92  Peshawar

#### Using between

In [35]:
df[df["Marks"].between(80, 90)]

   Student_ID   Name  Age Department  Marks        City
0         101    Ali   20         CS     85      Lahore
1         102  Ahmed   21         IT     90     Karachi
4         105  Usman   20         CS     88  Faisalabad

In [36]:
df[df["Age"].between(20, 22)]

   Student_ID    Name  Age Department  Marks        City
0         101     Ali   20         CS     85      Lahore
1         102   Ahmed   21         IT     90     Karachi
3         104  Ayesha   22         AI     92    Peshawar
4         105   Usman   20         CS     88  Faisalabad

####  Filtering in String

In [37]:
df[df["Name"].str.startswith("A")]

   Student_ID    Name  Age Department  Marks      City
0         101     Ali   20         CS     85    Lahore
1         102   Ahmed   21         IT     90   Karachi
3         104  Ayesha   22         AI     92  Peshawar

In [38]:
df[df["Name"].str.endswith("a")]

   Student_ID    Name  Age Department  Marks       City
2         103    Sara   19         SE     78  Islamabad
3         104  Ayesha   22         AI     92   Peshawar

In [39]:
df[df["Name"].str.contains("ar")]

   Student_ID  Name  Age Department  Marks       City
2         103  Sara   19         SE     78  Islamabad