#  Data Cleaning with Pandas

#### Importing pandas

In [27]:
import pandas as pd

#### Loading dataset

In [28]:
df=pd.read_csv("students.csv")
df

   Student_ID    Name  Age Department  Marks        City
0         101     Ali   20         CS     85      Lahore
1         102   Ahmed   21         IT     90     Karachi
2         103    Sara   19         SE     78   Islamabad
3         104  Ayesha   22         AI     92    Peshawar
4         105   Usman   20         CS     88  Faisalabad

#### Missing Values

Missing values are empty cells represented by **NaN**.

They can reduce model performance if not handled properly.

In [29]:
df.isnull()

   Student_ID   Name    Age  Department  Marks   City
0       False  False  False       False  False  False
1       False  False  False       False  False  False
2       False  False  False       False  False  False
3       False  False  False       False  False  False
4       False  False  False       False  False  False

In [30]:
df.isnull().sum()

Student_ID    0
Name          0
Age           0
Department    0
Marks         0
City          0
dtype: int64

In [31]:
df.isnull().sum().sum()

np.int64(0)

#### Droping missing values

In [32]:
df.dropna()

   Student_ID    Name  Age Department  Marks        City
0         101     Ali   20         CS     85      Lahore
1         102   Ahmed   21         IT     90     Karachi
2         103    Sara   19         SE     78   Islamabad
3         104  Ayesha   22         AI     92    Peshawar
4         105   Usman   20         CS     88  Faisalabad

#### Filling missing values

In [33]:
df.fillna(0)

   Student_ID    Name  Age Department  Marks        City
0         101     Ali   20         CS     85      Lahore
1         102   Ahmed   21         IT     90     Karachi
2         103    Sara   19         SE     78   Islamabad
3         104  Ayesha   22         AI     92    Peshawar
4         105   Usman   20         CS     88  Faisalabad

In [34]:
df["Age"] = df["Age"].fillna(df["Age"].mean())

In [35]:
df["Marks"] = df["Marks"].fillna(df["Marks"].median())

In [36]:
df["City"] = df["City"].fillna("Unknown")

#### Find duplicated rows

In [37]:
df.duplicated()

0    False
1    False
2    False
3    False
4    False
dtype: bool

In [38]:
df.duplicated().sum()

np.int64(0)

#### Removes the duplicated rows

In [39]:
df = df.drop_duplicates()
df

   Student_ID    Name  Age Department  Marks        City
0         101     Ali   20         CS     85      Lahore
1         102   Ahmed   21         IT     90     Karachi
2         103    Sara   19         SE     78   Islamabad
3         104  Ayesha   22         AI     92    Peshawar
4         105   Usman   20         CS     88  Faisalabad

##### Renaming columns

In [40]:
df.rename(columns={"Marks":"Score"})

   Student_ID    Name  Age Department  Score        City
0         101     Ali   20         CS     85      Lahore
1         102   Ahmed   21         IT     90     Karachi
2         103    Sara   19         SE     78   Islamabad
3         104  Ayesha   22         AI     92    Peshawar
4         105   Usman   20         CS     88  Faisalabad

In [41]:
df.rename(columns={
    "Marks":"Score",
    "Age":"Student_Age"
})

   Student_ID    Name  Student_Age Department  Score        City
0         101     Ali           20         CS     85      Lahore
1         102   Ahmed           21         IT     90     Karachi
2         103    Sara           19         SE     78   Islamabad
3         104  Ayesha           22         AI     92    Peshawar
4         105   Usman           20         CS     88  Faisalabad

#### Change the data type

In [42]:
df.dtypes

Student_ID     int64
Name          object
Age            int64
Department    object
Marks          int64
City          object
dtype: object

In [43]:
df["Student_ID"] = df["Student_ID"].astype(str)

#### Replace values

In [44]:
df["Department"] = df["Department"].replace("CS","Computer Science")
df

  Student_ID    Name  Age        Department  Marks        City
0        101     Ali   20  Computer Science     85      Lahore
1        102   Ahmed   21                IT     90     Karachi
2        103    Sara   19                SE     78   Islamabad
3        104  Ayesha   22                AI     92    Peshawar
4        105   Usman   20  Computer Science     88  Faisalabad

In [45]:
df["Department"] = df["Department"].replace({
    "CS":"Computer Science",
    "IT":"Information Technology"
})
df

  Student_ID    Name  Age              Department  Marks        City
0        101     Ali   20        Computer Science     85      Lahore
1        102   Ahmed   21  Information Technology     90     Karachi
2        103    Sara   19                      SE     78   Islamabad
3        104  Ayesha   22                      AI     92    Peshawar
4        105   Usman   20        Computer Science     88  Faisalabad

#### String cleaning

In [46]:
df["Name"] = df["Name"].str.strip()

In [47]:
df["Name"] = df["Name"].str.lower()

In [48]:
df["Name"] = df["Name"].str.upper()

In [49]:
df["Name"] = df["Name"].str.title()