#  GroupBy in Pandas

#### What is GroupBy?

`groupby()` divides the dataset into groups based on one or more columns.

After grouping, we can perform calculations such as:

- Sum
- Mean
- Maximum
- Minimum
- Count
- Standard Deviation
- Median

This follows the **Split → Apply → Combine** approach:

1. Split the data into groups.
2. Apply a function to each group.
3. Combine the results into a new table.

#### Importing pandas and reading the dataset

In [3]:
import pandas as pd 
df = pd.read_csv("students.csv")
df

   Student_ID    Name  Age Department  Marks        City
0         101     Ali   20         CS     85      Lahore
1         102   Ahmed   21         IT     90     Karachi
2         103    Sara   19         SE     78   Islamabad
3         104  Ayesha   22         AI     92    Peshawar
4         105   Usman   20         CS     88  Faisalabad

#### Grouopby one column

In [4]:
df.groupby("Department")["Marks"].mean()

Department
AI    92.0
CS    86.5
IT    90.0
SE    78.0
Name: Marks, dtype: float64

#### Aggeragation functions

In [5]:
df.groupby("Department")["Marks"].sum()

Department
AI     92
CS    173
IT     90
SE     78
Name: Marks, dtype: int64

In [6]:
df.groupby("Department")["Marks"].max()

Department
AI    92
CS    88
IT    90
SE    78
Name: Marks, dtype: int64

In [7]:
df.groupby("Department")["Marks"].min()

Department
AI    92
CS    85
IT    90
SE    78
Name: Marks, dtype: int64

In [8]:
df.groupby("Department")["Marks"].count()

Department
AI    1
CS    2
IT    1
SE    1
Name: Marks, dtype: int64

In [9]:
df.groupby("Department")["Marks"].std()

Department
AI        NaN
CS    2.12132
IT        NaN
SE        NaN
Name: Marks, dtype: float64

In [10]:
df.groupby("Department")["Marks"].median()

Department
AI    92.0
CS    86.5
IT    90.0
SE    78.0
Name: Marks, dtype: float64

#### Multiple Aggeragation functions

In [11]:
df.groupby("Department")["Marks"].agg(
    ["mean", "max", "min", "sum", "count"]
)

            mean  max  min  sum  count
Department
AI          92.0   92   92   92      1
CS          86.5   88   85  173      2
IT          90.0   90   90   90      1
SE          78.0   78   78   78      1

#### Groupby by Multiple columns

In [12]:
df.groupby(
    ["Department", "City"]
)["Marks"].mean()

Department  City
AI          Peshawar      92.0
CS          Faisalabad    88.0
            Lahore        85.0
IT          Karachi       90.0
SE          Islamabad     78.0
Name: Marks, dtype: float64