#  Spam Email Detection using Natural Language Processing (NLP)

#### Project Overview

This project aims to build a Machine Learning model that automatically classifies emails as **Spam** or **Not Spam (Ham)**. The project uses Natural Language Processing (NLP) techniques to preprocess text, convert it into numerical features using the **Bag of Words (BoW)** method, train multiple classification models, compare their performance, and build a prediction pipeline for classifying new email messages.

---

#### Objectives

- Build an email spam detection system.
- Perform text preprocessing using NLP.
- Convert text into numerical features using Bag of Words.
- Train multiple Machine Learning models.
- Compare model performance.
- Select the best-performing model.
- Create a user prediction pipeline.

---

#### Dataset

The dataset contains email messages and their corresponding labels.

- **Text** → Email content
- **Label** → Spam or Ham (Not Spam)

---


#### Text Preprocessing

The following preprocessing steps were applied:

- Convert text to lowercase
- Remove HTML tags
- Remove URLs
- Remove punctuation
- Remove numbers
- Remove extra spaces
- Tokenization
- Remove stop words
- Lemmatization
- Join tokens into complete sentences

---

#### Feature Engineering

The cleaned text was transformed into numerical features using the **Bag of Words (CountVectorizer)** technique.

---

#### Machine Learning Models

The following models were trained and compared:

- Multinomial Naive Bayes
- Logistic Regression
- SVM
---

#### Model Evaluation

The models were evaluated using:

- Accuracy

The model with the best performance was selected for the final prediction pipeline.

---

#### Prediction Pipeline

The final prediction pipeline performs the following steps:

1. Accepts an email from the user.
2. Applies the same preprocessing used during training.
3. Converts the email into Bag of Words features.
4. Predicts whether the email is **Spam** or **Not Spam (Ham)**.
5. Displays the prediction result.

---

#### Skills Demonstrated

- Natural Language Processing (NLP)
- Text Preprocessing
- Feature Engineering
- Bag of Words
- Machine Learning
- Model Evaluation
- Prediction Pipeline Development

---

#### Conclusion

This project demonstrates a complete end-to-end NLP workflow for spam email classification. It includes text preprocessing, feature extraction using Bag of Words, training and comparing multiple Machine Learning models, selecting the best-performing model, and building a prediction pipeline for real-world email classification.

Importing Libraries

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import re
import string
from bs4 import BeautifulSoup
from textblob import TextBlob
import nltk
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords
from nltk.stem import PorterStemmer
from nltk.stem import WordNetLemmatizer
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.model_selection import train_test_split
from gensim.models import Word2Vec
from sklearn.naive_bayes import MultinomialNB
from sklearn.svm import SVC
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import (
    accuracy_score,
)
import warnings
warnings.filterwarnings("ignore")

Load the dataset

In [2]:
data=pd.read_csv(r"F:\Anas\DATA_SCIENCE_PROJECTS\DATASETS\combined_data.csv")
data.head()

   label                                               text
0      1  ounce feather bowl hummingbird opec moment ala...
1      1  wulvob get your medircations online qnb ikud v...
2      0   computer connection from cnn com wednesday es...
3      1  university degree obtain a prosperous future m...
4      0  thanks for all your answers guys i know i shou...

Taking sample from the data

In [3]:
data= data.sample(n=10000, random_state=42)

print(data.shape)

(10000, 2)

In [4]:
data.shape

(10000, 2)

In [5]:
data.isnull().sum()

label    0
text     0
dtype: int64

In [6]:
data.info()

<class 'pandas.DataFrame'>
Index: 10000 entries, 67681 to 31918
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   label   10000 non-null  int64
 1   text    10000 non-null  str
dtypes: int64(1), str(1)
memory usage: 234.4 KB

In [7]:
data["label"].value_counts()

label
1    5224
0    4776
Name: count, dtype: int64

Data Preprocessing

In [8]:
data[~data["text"].str.islower()]

       label                                               text
61209      1  html >\nÝnternette kendÝnÝzÝ daha ÝyÝ hÝssedec...
56122      1  from mrs victoria igor\nemails : victorigor @ ...
44881      1  dear sir ,\n* öðâ · í ¨ åäüþ ³ § óð ¶ àäêéú ² ...
43587      1  good day ,\nthis mail will definitely be comin...
20331      1                                                .\n
14115      1  faturasiz\nÝletÝÞÝm\nuluslararasý telefon\ngör...

In [9]:
#convering the data into lowe case
data.text=data.text.str.lower()
data.head()

       label                                               text
67681      0  accuweather escapenumber day forecast for beve...
61385      1  dear in christ the time has come for christian...
41829      1  hallway cosponsor pry reimbursable coat clumsy...
29172      1  does size matter' escapenumber of women said t...
35274      0  along zeng wrote hi all is there levene' test ...

In [10]:
#removes the html tages
data.text=data.text.apply(lambda x: BeautifulSoup(x, 'html.parser').get_text())
data.head()

       label                                               text
67681      0  accuweather escapenumber day forecast for beve...
61385      1  dear in christ the time has come for christian...
41829      1  hallway cosponsor pry reimbursable coat clumsy...
29172      1  does size matter' escapenumber of women said t...
35274      0  along zeng wrote hi all is there levene' test ...

In [11]:
#removes the numbers
data.text=data.text.apply(lambda x: re.sub(r'\d+', '', x))
data.head()

       label                                               text
67681      0  accuweather escapenumber day forecast for beve...
61385      1  dear in christ the time has come for christian...
41829      1  hallway cosponsor pry reimbursable coat clumsy...
29172      1  does size matter' escapenumber of women said t...
35274      0  along zeng wrote hi all is there levene' test ...

In [12]:
#removes the punctuations
data.text=data.text.apply(lambda x: x.translate(str.maketrans('', '', string.punctuation)))
data.head()

       label                                               text
67681      0  accuweather escapenumber day forecast for beve...
61385      1  dear in christ the time has come for christian...
41829      1  hallway cosponsor pry reimbursable coat clumsy...
29172      1  does size matter escapenumber of women said th...
35274      0  along zeng wrote hi all is there levene test i...

In [13]:
#removes the urls
data.text=data.text.apply(lambda x: re.sub(r'http\S+', '', x))
data.head()

       label                                               text
67681      0  accuweather escapenumber day forecast for beve...
61385      1  dear in christ the time has come for christian...
41829      1  hallway cosponsor pry reimbursable coat clumsy...
29172      1  does size matter escapenumber of women said th...
35274      0  along zeng wrote hi all is there levene test i...

In [14]:
#removes the extra spaces
data.text=data.text.apply(lambda x: " ".join(x.split()))
data.head()

       label                                               text
67681      0  accuweather escapenumber day forecast for beve...
61385      1  dear in christ the time has come for christian...
41829      1  hallway cosponsor pry reimbursable coat clumsy...
29172      1  does size matter escapenumber of women said th...
35274      0  along zeng wrote hi all is there levene test i...

In [15]:
#cehcking for the urls
url_rows = data[data['text'].str.contains(r'http\S+|www\S+', regex=True, na=False)]
url_rows

       label                                               text
61428      1  very hot peport http wwwescapenumber uploadesc...
73037      1  very hot peport http wwwescapenumber uploadesc...
49891      0  thank you for your suggestion i tried with dif...
8621       1  ¦vcov ûìì×aðî«ìahxæê...

In [16]:
#converting the text into tokens by using nltk library
from nltk.tokenize import word_tokenize
data["text"] = data["text"].apply(lambda x: word_tokenize(x))
data.head()

       label                                               text
67681      0  [accuweather, escapenumber, day, forecast, for...
61385      1  [dear, in, christ, the, time, has, come, for, ...
41829      1  [hallway, cosponsor, pry, reimbursable, coat, ...
29172      1  [does, size, matter, escapenumber, of, women, ...
35274      0  [along, zeng, wrote, hi, all, is, there, leven...

In [17]:
stop_words = set(stopwords.words("english"))
data["text"] = data["text"].apply(
    lambda words: [word for word in words if word.lower() not in stop_words]
)

data.head()

       label                                               text
67681      0  [accuweather, escapenumber, day, forecast, bev...
61385      1  [dear, christ, time, come, christians, worship...
41829      1  [hallway, cosponsor, pry, reimbursable, coat, ...
29172      1  [size, matter, escapenumber, women, said, thay...
35274      0  [along, zeng, wrote, hi, levene, test, r, coul...

In [18]:
lemmatizer = WordNetLemmatizer()
data["text"] = data["text"].apply(
    lambda words: [lemmatizer.lemmatize(word) for word in words]
)
data.head()

       label                                               text
67681      0  [accuweather, escapenumber, day, forecast, bev...
61385      1  [dear, christ, time, come, christian, worship,...
41829      1  [hallway, cosponsor, pry, reimbursable, coat, ...
29172      1  [size, matter, escapenumber, woman, said, thay...
35274      0  [along, zeng, wrote, hi, levene, test, r, coul...

In [19]:
print(type(data["text"].iloc[0]))
print(data["text"].iloc[0])

<class 'list'>
['accuweather', 'escapenumber', 'day', 'forecast', 'beverly', 'hill', 'tonight', 'l', 'escapenumber', 'moonlit', 'sky', 'tomorrow', 'h', 'escapenumber', 'sunny', 'tomorrow', 'night', 'l', 'escapenumber', 'low', 'cloud', 'fog', 'forming', 'tuesday', 'h', 'escapenumber', 'l', 'escapenumber', 'fog', 'sun', 'wednesday', 'h', 'escapenumber', 'l', 'escapenumber', 'area', 'fog', 'sun', 'thursday', 'h', 'escapenumber', 'l', 'escapenumber', 'mostly', 'sunny', 'cool', 'friday', 'h', 'escapenumber', 'l', 'escapenumber', 'mostly', 'sunny', 'cool', 'saturday', 'h', 'escapenumber', 'l', 'escapenumber', 'mostly', 'sunny', 'cool', 'choose', 'another', 'forecast', 'enter', 'zipcode', 'city', 'state', '©escapenumber', 'accuweather', 'inc', 'right', 'reserved']

In [20]:
data["text"] = data["text"].apply(lambda x: " ".join(x))
data.head()

       label                                               text
67681      0  accuweather escapenumber day forecast beverly ...
61385      1  dear christ time come christian worship god sp...
41829      1  hallway cosponsor pry reimbursable coat clumsy...
29172      1  size matter escapenumber woman said thay unhap...
35274      0  along zeng wrote hi levene test r could give a...

In [21]:
vectorizer = CountVectorizer()
X = vectorizer.fit_transform(data["text"])
X

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 914101 stored elements and shape (10000, 86418)>

In [22]:
y=data["label"]

In [23]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((8000, 86418), (2000, 86418), (8000,), (2000,))

In [24]:
naive_bayes = MultinomialNB()

svm = SVC()

logistic_regression = LogisticRegression(max_iter=1000)

In [25]:
naive_bayes.fit(X_train, y_train)

svm.fit(X_train, y_train)

logistic_regression.fit(X_train, y_train)

LogisticRegression(max_iter=1000)

In [26]:
nb_prediction = naive_bayes.predict(X_test)

svm_prediction = svm.predict(X_test)

lr_prediction = logistic_regression.predict(X_test)

In [27]:
nb_accuracy = accuracy_score(y_test, nb_prediction)

svm_accuracy = accuracy_score(y_test, svm_prediction)

lr_accuracy = accuracy_score(y_test, lr_prediction)
print("Naive Bayes Accuracy:", nb_accuracy)

print("SVM Accuracy:", svm_accuracy)

print("Logistic Regression Accuracy:", lr_accuracy)

Naive Bayes Accuracy: 0.9655
SVM Accuracy: 0.859
Logistic Regression Accuracy: 0.9725

In [28]:
results = {
    "Naive Bayes": nb_accuracy,
    "SVM": svm_accuracy,
    "Logistic Regression": lr_accuracy
}

for model, accuracy in results.items():
    print(f"{model}: {accuracy:.4f}")

Naive Bayes: 0.9655
SVM: 0.8590
Logistic Regression: 0.9725

In [29]:
best_model = max(results, key=results.get)

print("Best Model:", best_model)

print("Best Accuracy:", results[best_model])

Best Model: Logistic Regression
Best Accuracy: 0.9725

In [36]:
def predict_email():

    # Take user input
    email = input("Enter your email message:\n")

    # 1. Lowercase
    email = email.lower()

    # 2. Remove HTML
    email = BeautifulSoup(email, "html.parser").get_text()

    # 3. Remove URLs
    email = re.sub(r'http\S+|www\S+', '', email)

    # 4. Remove punctuation
    email = email.translate(str.maketrans('', '', string.punctuation))

    # 5. Remove numbers
    email = re.sub(r'\d+', '', email)

    # 6. Remove extra spaces
    email = " ".join(email.split())

    # 7. Tokenization
    words = word_tokenize(email)

    # 8. Remove stop words
    words = [word for word in words if word not in stop_words]

    # 9. Lemmatization
    words = [lemmatizer.lemmatize(word) for word in words]

    # 10. Join words
    email = " ".join(words)

    # 11. Bag of Words
    email_vector = vectorizer.transform([email])

    # 12. Prediction
    prediction = logistic_regression.predict(email_vector)

    # 13. Probability
    probability = logistic_regression.predict_proba(email_vector)

    # 14. Result
    if prediction[0] == 1:
        print("\n🚨 Spam Email")
    else:
        print("\n✅ Not Spam (Ham)")

    print(f"Confidence: {max(probability[0]) * 100:.2f}%")
predict_email()

🚨 Spam Email
Confidence: 72.19%

In [37]:
import joblib

# Save trained model
joblib.dump(logistic_regression, "spam_model.pkl")

# Save trained vectorizer
joblib.dump(vectorizer, "tfidf_vectorizer.pkl")

print("Model and vectorizer saved successfully!")

Model and vectorizer saved successfully!