# Mathematical Features

Mathematical Feature Engineering is the process of creating new features by applying mathematical operations to existing numerical features.

These transformations can help machine learning models discover relationships that may not be obvious from the original features.

Common mathematical operations include:

- Addition
- Subtraction
- Multiplication
- Division
- Power
- Absolute Value
- Logarithm
- Square Root

In [1]:
import pandas as pd

df = pd.DataFrame({
    "Price": [100, 200, 300, 400, 500],
    "Quantity": [2, 3, 4, 5, 6],
    "Discount": [10, 20, 30, 40, 50]
})

df

   Price  Quantity  Discount
0    100         2        10
1    200         3        20
2    300         4        30
3    400         5        40
4    500         6        50

## Addition Features

We can combine two numerical features using addition.

For example:

Total = Price + Discount

Mathematical operations can create new information from existing features.

In [2]:
df["Price_Discount_Total"] = (
    df["Price"] + df["Discount"]
)

df

   Price  Quantity  Discount  Price_Discount_Total
0    100         2        10                   110
1    200         3        20                   220
2    300         4        30                   330
3    400         5        40                   440
4    500         6        50                   550

## Subtraction Features

Subtraction can be used to calculate differences between numerical features.

For example:

Price Difference = Price - Discount

In [3]:
df["Price_After_Discount"] = (
    df["Price"] - df["Discount"]
)

df

   Price  Quantity  Discount  Price_Discount_Total  Price_After_Discount
0    100         2        10                   110                    90
1    200         3        20                   220                   180
2    300         4        30                   330                   270
3    400         5        40                   440                   360
4    500         6        50                   550                   450

## Multiplication Features

Multiplication can be used to create meaningful features from two numerical variables.

For example:

Total Cost = Price × Quantity

In [4]:
df["Total_Cost"] = (
    df["Price"] * df["Quantity"]
)

df

,Price,Quantity,Discount,Price_Discount_Total,Price_After_Discount,Total_Cost
0,100,2,10,110,90,200
1,200,3,20,220,180,600
2,300,4,30,330,270,1200
3,400,5,40,440,360,2000
4,500,6,50,550,450,3000

## Division Features

Division can be used to create ratios between features.

For example:

Price Per Unit = Total Cost / Quantity

In [5]:
df["Price_Per_Unit"] = (
    df["Total_Cost"] / df["Quantity"]
)

df

,Price,Quantity,Discount,Price_Discount_Total,Price_After_Discount,Total_Cost,Price_Per_Unit
0,100,2,10,110,90,200,100.0
1,200,3,20,220,180,600,200.0
2,300,4,30,330,270,1200,300.0
3,400,5,40,440,360,2000,400.0
4,500,6,50,550,450,3000,500.0

## Ratio Features

Ratios are commonly used in feature engineering because they describe the relationship between two numerical features.

Example:

Discount Ratio = Discount / Price

A ratio can sometimes provide more useful information than the original features.

In [6]:
df["Discount_Ratio"] = (
    df["Discount"] / df["Price"]
)

df

,Price,Quantity,Discount,Price_Discount_Total,Price_After_Discount,Total_Cost,Price_Per_Unit,Discount_Ratio
0,100,2,10,110,90,200,100.0,0.1
1,200,3,20,220,180,600,200.0,0.1
2,300,4,30,330,270,1200,300.0,0.1
3,400,5,40,440,360,2000,400.0,0.1
4,500,6,50,550,450,3000,500.0,0.1

## Power Features

We can create new features by raising an existing feature to a power.

Examples:

x²
x³
√x

Polynomial features can help models capture non-linear relationships.

In [7]:
df["Price_Squared"] = df["Price"] ** 2

df["Price_Cubed"] = df["Price"] ** 3

df

,Price,Quantity,Discount,Price_Discount_Total,Price_After_Discount,Total_Cost,Price_Per_Unit,Discount_Ratio,Price_Squared,Price_Cubed
0,100,2,10,110,90,200,100.0,0.1,10000,1000000
1,200,3,20,220,180,600,200.0,0.1,40000,8000000
2,300,4,30,330,270,1200,300.0,0.1,90000,27000000
3,400,5,40,440,360,2000,400.0,0.1,160000,64000000
4,500,6,50,550,450,3000,500.0,0.1,250000,125000000

## Absolute Value Features

The absolute value removes the sign of a number.

For example:

|-10| = 10

This can be useful when only the magnitude of a difference is important.

In [8]:
df["Price_Difference"] = (
    df["Price"] - df["Discount"]
)

df["Absolute_Difference"] = (
    df["Price_Difference"].abs()
)

df

,Price,Quantity,Discount,Price_Discount_Total,Price_After_Discount,Total_Cost,Price_Per_Unit,Discount_Ratio,Price_Squared,Price_Cubed,Price_Difference,Absolute_Difference
0,100,2,10,110,90,200,100.0,0.1,10000,1000000,90,90
1,200,3,20,220,180,600,200.0,0.1,40000,8000000,180,180
2,300,4,30,330,270,1200,300.0,0.1,90000,27000000,270,270
3,400,5,40,440,360,2000,400.0,0.1,160000,64000000,360,360
4,500,6,50,550,450,3000,500.0,0.1,250000,125000000,450,450

## Logarithmic Features

Logarithmic transformation can compress large numerical values.

It is particularly useful for highly right-skewed features.

For non-negative data, we can use:

log(1 + x)

In [9]:
import numpy as np

df["Price_Log"] = np.log1p(df["Price"])

df

,Price,Quantity,Discount,Price_Discount_Total,Price_After_Discount,Total_Cost,Price_Per_Unit,Discount_Ratio,Price_Squared,Price_Cubed,Price_Difference,Absolute_Difference,Price_Log
0,100,2,10,110,90,200,100.0,0.1,10000,1000000,90,90,4.615121
1,200,3,20,220,180,600,200.0,0.1,40000,8000000,180,180,5.303305
2,300,4,30,330,270,1200,300.0,0.1,90000,27000000,270,270,5.707110
3,400,5,40,440,360,2000,400.0,0.1,160000,64000000,360,360,5.993961
4,500,6,50,550,450,3000,500.0,0.1,250000,125000000,450,450,6.216606

## Square Root Features

Square root transformation can be useful for reducing moderate right skewness.

Formula:

√x

In [10]:
df["Price_Sqrt"] = np.sqrt(df["Price"])

df

,Price,Quantity,Discount,Price_Discount_Total,Price_After_Discount,Total_Cost,Price_Per_Unit,Discount_Ratio,Price_Squared,Price_Cubed,Price_Difference,Absolute_Difference,Price_Log,Price_Sqrt
0,100,2,10,110,90,200,100.0,0.1,10000,1000000,90,90,4.615121,10.000000
1,200,3,20,220,180,600,200.0,0.1,40000,8000000,180,180,5.303305,14.142136
2,300,4,30,330,270,1200,300.0,0.1,90000,27000000,270,270,5.707110,17.320508
3,400,5,40,440,360,2000,400.0,0.1,160000,64000000,360,360,5.993961,20.000000
4,500,6,50,550,450,3000,500.0,0.1,250000,125000000,450,450,6.216606,22.360680