# Ratio Features

Ratio Feature Engineering creates a new feature by dividing one numerical feature by another.

A ratio describes the relationship between two variables.

General formula:

Ratio = Feature A / Feature B

Ratio features are useful when the relationship between two variables is more meaningful than their individual values.

## Why Do We Create Ratio Features?

Two individual features may not fully describe a relationship.

For example:

- Income
- Expenses

Instead of using only these two features, we can create:

Savings Ratio = Expenses / Income

This can provide the model with additional information about the relationship between income and expenses.

In [1]:
import pandas as pd

df = pd.DataFrame({
    "Income": [30000, 40000, 50000, 60000, 80000],
    "Expenses": [15000, 20000, 30000, 30000, 40000],
    "Age": [20, 25, 30, 35, 40]
})

df

   Income  Expenses  Age
0   30000     15000   20
1   40000     20000   25
2   50000     30000   30
3   60000     30000   35
4   80000     40000   40

## Creating a Basic Ratio

We can calculate the ratio between two numerical features.

For example:

Expense Ratio = Expenses / Income

This tells us how large the expenses are relative to income.

In [2]:
df["Expense_Ratio"] = (
    df["Expenses"] / df["Income"]
)

df

   Income  Expenses  Age  Expense_Ratio
0   30000     15000   20            0.5
1   40000     20000   25            0.5
2   50000     30000   30            0.6
3   60000     30000   35            0.5
4   80000     40000   40            0.5

## Ratio as a Percentage

A ratio can also be converted into a percentage.

Formula:

Percentage = Ratio × 100

For example:

Expense Ratio = 0.5

Expense Percentage = 0.5 × 100 = 50%

This means expenses are 50% of income.

In [3]:
df["Expense_Percentage"] = (
    df["Expense_Ratio"] * 100
)

df

   Income  Expenses  Age  Expense_Ratio  Expense_Percentage
0   30000     15000   20            0.5                50.0
1   40000     20000   25            0.5                50.0
2   50000     30000   30            0.6                60.0
3   60000     30000   35            0.5                50.0
4   80000     40000   40            0.5                50.0

## Price Per Unit

A common real-world ratio feature is calculating the value per unit.

Formula:

Price Per Unit = Total Price / Quantity

In [4]:
df = pd.DataFrame({
    "Total_Price": [1000, 2000, 3000, 5000, 8000],
    "Quantity": [10, 20, 30, 25, 40]
})

df["Price_Per_Unit"] = (
    df["Total_Price"] / df["Quantity"]
)

df

   Total_Price  Quantity  Price_Per_Unit
0         1000        10           100.0
1         2000        20           100.0
2         3000        30           100.0
3         5000        25           200.0
4         8000        40           200.0

## Business Ratio Example

Financial datasets commonly contain useful ratio features.

Examples:

- Profit Margin = Profit / Revenue
- Debt Ratio = Debt / Assets
- Expense Ratio = Expenses / Income
- Return on Investment = Profit / Investment

These ratios can provide more meaningful information than raw values alone.

In [5]:
df = pd.DataFrame({
    "Revenue": [100000, 150000, 200000, 300000],
    "Profit": [10000, 30000, 50000, 90000]
})

df["Profit_Margin"] = (
    df["Profit"] / df["Revenue"]
)

df

   Revenue  Profit  Profit_Margin
0   100000   10000           0.10
1   150000   30000           0.20
2   200000   50000           0.25
3   300000   90000           0.30

## Handling Division by Zero

Ratio features can create problems when the denominator contains zero.

For example:

Ratio = A / B

If:

B = 0

the result becomes undefined or infinite.

Therefore, zero denominators must be handled carefully.

In [6]:
import numpy as np

df = pd.DataFrame({
    "Income": [30000, 40000, 0, 60000],
    "Expenses": [15000, 20000, 10000, 30000]
})

df["Expense_Ratio"] = (
    df["Expenses"] /
    df["Income"].replace(0, np.nan)
)

df

   Income  Expenses  Expense_Ratio
0   30000     15000            0.5
1   40000     20000            0.5
2       0     10000            NaN
3   60000     30000            0.5

In [7]:
df["Expense_Ratio"] = (
    df["Expense_Ratio"]
    .replace([np.inf, -np.inf], np.nan)
)

df

   Income  Expenses  Expense_Ratio
0   30000     15000            0.5
1   40000     20000            0.5
2       0     10000            NaN
3   60000     30000            0.5