# DateTime Features

DateTime Feature Engineering is the process of extracting useful information from date and time values.

A single datetime column can contain many useful features, such as:

- Year
- Month
- Day
- Day of Week
- Hour
- Minute
- Second
- Quarter
- Week of Year
- Weekend
- Time of Day

These features can help machine learning models understand patterns related to time.

In [38]:
import pandas as pd

df = pd.DataFrame({
    "Date": [
        "2026-01-15 08:30:00",
        "2026-02-20 14:45:00",
        "2026-03-25 18:15:00",
        "2026-04-10 21:00:00",
        "2026-05-05 10:20:00"
    ]
})

df

                  Date
0  2026-01-15 08:30:00
1  2026-02-20 14:45:00
2  2026-03-25 18:15:00
3  2026-04-10 21:00:00
4  2026-05-05 10:20:00

## Converting Data to Datetime

Before extracting datetime features, the date column should be converted into pandas datetime format.

We can use:

`pd.to_datetime()`

This allows us to easily extract different components from the date.

In [39]:
df["Date"] = pd.to_datetime(df["Date"])

df.dtypes

Date    datetime64[us]
dtype: object

In [40]:
df["Year"] = df["Date"].dt.year

df

                 Date  Year
0 2026-01-15 08:30:00  2026
1 2026-02-20 14:45:00  2026
2 2026-03-25 18:15:00  2026
3 2026-04-10 21:00:00  2026
4 2026-05-05 10:20:00  2026

In [41]:
df["Month"] = df["Date"].dt.month

df

                 Date  Year  Month
0 2026-01-15 08:30:00  2026      1
1 2026-02-20 14:45:00  2026      2
2 2026-03-25 18:15:00  2026      3
3 2026-04-10 21:00:00  2026      4
4 2026-05-05 10:20:00  2026      5

In [42]:
df["Day"] = df["Date"].dt.day

df

                 Date  Year  Month  Day
0 2026-01-15 08:30:00  2026      1   15
1 2026-02-20 14:45:00  2026      2   20
2 2026-03-25 18:15:00  2026      3   25
3 2026-04-10 21:00:00  2026      4   10
4 2026-05-05 10:20:00  2026      5    5

## Day of Week

The day of the week can be useful because many real-world activities depend on weekdays and weekends.

Examples:

- Monday = 0
- Tuesday = 1
- Wednesday = 2
- ...
- Sunday = 6

In [43]:
df["Day_of_Week"] = df["Date"].dt.dayofweek

df

                 Date  Year  Month  Day  Day_of_Week
0 2026-01-15 08:30:00  2026      1   15            3
1 2026-02-20 14:45:00  2026      2   20            4
2 2026-03-25 18:15:00  2026      3   25            2
3 2026-04-10 21:00:00  2026      4   10            4
4 2026-05-05 10:20:00  2026      5    5            1

In [44]:
df["Day_Name"] = df["Date"].dt.day_name()

df

                 Date  Year  Month  Day  Day_of_Week   Day_Name
0 2026-01-15 08:30:00  2026      1   15            3   Thursday
1 2026-02-20 14:45:00  2026      2   20            4     Friday
2 2026-03-25 18:15:00  2026      3   25            2  Wednesday
3 2026-04-10 21:00:00  2026      4   10            4     Friday
4 2026-05-05 10:20:00  2026      5    5            1    Tuesday

## Weekend Feature

We can create a binary feature that identifies whether a date falls on a weekend.

Saturday and Sunday → 1

Monday to Friday → 0

In [45]:
df["Is_Weekend"] = (
    df["Date"].dt.dayofweek >= 5
).astype(int)

df

                 Date  Year  Month  Day  Day_of_Week   Day_Name  Is_Weekend
0 2026-01-15 08:30:00  2026      1   15            3   Thursday           0
1 2026-02-20 14:45:00  2026      2   20            4     Friday           0
2 2026-03-25 18:15:00  2026      3   25            2  Wednesday           0
3 2026-04-10 21:00:00  2026      4   10            4     Friday           0
4 2026-05-05 10:20:00  2026      5    5            1    Tuesday           0

In [46]:
df["Hour"] = df["Date"].dt.hour

df

,Date,Year,Month,Day,Day_of_Week,Day_Name,Is_Weekend,Hour
0,2026-01-15 08:30:00,2026,1,15,3,Thursday,0,8
1,2026-02-20 14:45:00,2026,2,20,4,Friday,0,14
2,2026-03-25 18:15:00,2026,3,25,2,Wednesday,0,18
3,2026-04-10 21:00:00,2026,4,10,4,Friday,0,21
4,2026-05-05 10:20:00,2026,5,5,1,Tuesday,0,10

In [47]:
df["Minute"] = df["Date"].dt.minute
df["Second"] = df["Date"].dt.second

df

,Date,Year,Month,Day,Day_of_Week,Day_Name,Is_Weekend,Hour,Minute,Second
0,2026-01-15 08:30:00,2026,1,15,3,Thursday,0,8,30,0
1,2026-02-20 14:45:00,2026,2,20,4,Friday,0,14,45,0
2,2026-03-25 18:15:00,2026,3,25,2,Wednesday,0,18,15,0
3,2026-04-10 21:00:00,2026,4,10,4,Friday,0,21,0,0
4,2026-05-05 10:20:00,2026,5,5,1,Tuesday,0,10,20,0

## Quarter

A year is divided into four quarters:

- Q1 → January to March
- Q2 → April to June
- Q3 → July to September
- Q4 → October to December

Quarter information can be useful for business and seasonal analysis.

In [48]:
df["Quarter"] = df["Date"].dt.quarter

df

,Date,Year,Month,Day,Day_of_Week,Day_Name,Is_Weekend,Hour,Minute,Second,Quarter
0,2026-01-15 08:30:00,2026,1,15,3,Thursday,0,8,30,0,1
1,2026-02-20 14:45:00,2026,2,20,4,Friday,0,14,45,0,1
2,2026-03-25 18:15:00,2026,3,25,2,Wednesday,0,18,15,0,1
3,2026-04-10 21:00:00,2026,4,10,4,Friday,0,21,0,0,2
4,2026-05-05 10:20:00,2026,5,5,1,Tuesday,0,10,20,0,2

In [49]:
df["Week_of_Year"] = (
    df["Date"].dt.isocalendar().week
)

df

,Date,Year,Month,Day,Day_of_Week,Day_Name,Is_Weekend,Hour,Minute,Second,Quarter,Week_of_Year
0,2026-01-15 08:30:00,2026,1,15,3,Thursday,0,8,30,0,1,3
1,2026-02-20 14:45:00,2026,2,20,4,Friday,0,14,45,0,1,8
2,2026-03-25 18:15:00,2026,3,25,2,Wednesday,0,18,15,0,1,13
3,2026-04-10 21:00:00,2026,4,10,4,Friday,0,21,0,0,2,15
4,2026-05-05 10:20:00,2026,5,5,1,Tuesday,0,10,20,0,2,19

In [50]:
df["Day_of_Year"] = df["Date"].dt.dayofyear

df

,Date,Year,Month,Day,Day_of_Week,Day_Name,Is_Weekend,Hour,Minute,Second,Quarter,Week_of_Year,Day_of_Year
0,2026-01-15 08:30:00,2026,1,15,3,Thursday,0,8,30,0,1,3,15
1,2026-02-20 14:45:00,2026,2,20,4,Friday,0,14,45,0,1,8,51
2,2026-03-25 18:15:00,2026,3,25,2,Wednesday,0,18,15,0,1,13,84
3,2026-04-10 21:00:00,2026,4,10,4,Friday,0,21,0,0,2,15,100
4,2026-05-05 10:20:00,2026,5,5,1,Tuesday,0,10,20,0,2,19,125

## Time of Day

We can convert the hour into meaningful categories.

Example:

- Morning
- Afternoon
- Evening
- Night

This can be useful for applications such as:

- Sales prediction
- Traffic prediction
- Website activity
- Customer behavior

In [51]:
def time_of_day(hour):
    
    if 5 <= hour < 12:
        return "Morning"
    
    elif 12 <= hour < 17:
        return "Afternoon"
    
    elif 17 <= hour < 21:
        return "Evening"
    
    else:
        return "Night"


df["Time_of_Day"] = df["Hour"].apply(time_of_day)

df

,Date,Year,Month,Day,Day_of_Week,Day_Name,Is_Weekend,Hour,Minute,Second,Quarter,Week_of_Year,Day_of_Year,Time_of_Day
0,2026-01-15 08:30:00,2026,1,15,3,Thursday,0,8,30,0,1,3,15,Morning
1,2026-02-20 14:45:00,2026,2,20,4,Friday,0,14,45,0,1,8,51,Afternoon
2,2026-03-25 18:15:00,2026,3,25,2,Wednesday,0,18,15,0,1,13,84,Evening
3,2026-04-10 21:00:00,2026,4,10,4,Friday,0,21,0,0,2,15,100,Night
4,2026-05-05 10:20:00,2026,5,5,1,Tuesday,0,10,20,0,2,19,125,Morning

In [52]:
df["Month_Name"] = df["Date"].dt.month_name()

df

,Date,Year,Month,Day,Day_of_Week,Day_Name,Is_Weekend,Hour,Minute,Second,Quarter,Week_of_Year,Day_of_Year,Time_of_Day,Month_Name
0,2026-01-15 08:30:00,2026,1,15,3,Thursday,0,8,30,0,1,3,15,Morning,January
1,2026-02-20 14:45:00,2026,2,20,4,Friday,0,14,45,0,1,8,51,Afternoon,February
2,2026-03-25 18:15:00,2026,3,25,2,Wednesday,0,18,15,0,1,13,84,Evening,March
3,2026-04-10 21:00:00,2026,4,10,4,Friday,0,21,0,0,2,15,100,Night,April
4,2026-05-05 10:20:00,2026,5,5,1,Tuesday,0,10,20,0,2,19,125,Morning,May

In [53]:
df["Month_Start"] = df["Date"].dt.is_month_start
df["Month_End"] = df["Date"].dt.is_month_end

df

,Date,Year,Month,Day,Day_of_Week,Day_Name,Is_Weekend,Hour,Minute,Second,Quarter,Week_of_Year,Day_of_Year,Time_of_Day,Month_Name,Month_Start,Month_End
0,2026-01-15 08:30:00,2026,1,15,3,Thursday,0,8,30,0,1,3,15,Morning,January,False,False
1,2026-02-20 14:45:00,2026,2,20,4,Friday,0,14,45,0,1,8,51,Afternoon,February,False,False
2,2026-03-25 18:15:00,2026,3,25,2,Wednesday,0,18,15,0,1,13,84,Evening,March,False,False
3,2026-04-10 21:00:00,2026,4,10,4,Friday,0,21,0,0,2,15,100,Night,April,False,False
4,2026-05-05 10:20:00,2026,5,5,1,Tuesday,0,10,20,0,2,19,125,Morning,May,False,False

## Date Difference

We can calculate the number of days between two dates.

This is useful for features such as:

- Customer age
- Days since purchase
- Days since last login
- Subscription duration
- Delivery time

In [54]:
df_dates = pd.DataFrame({
    "Order_Date": pd.to_datetime([
        "2026-01-01",
        "2026-01-10",
        "2026-02-01"
    ]),
    
    "Delivery_Date": pd.to_datetime([
        "2026-01-05",
        "2026-01-15",
        "2026-02-08"
    ])
})

df_dates["Delivery_Days"] = (
    df_dates["Delivery_Date"] -
    df_dates["Order_Date"]
).dt.days

df_dates

  Order_Date Delivery_Date  Delivery_Days
0 2026-01-01    2026-01-05              4
1 2026-01-10    2026-01-15              5
2 2026-02-01    2026-02-08              7

## Creating Age from Date of Birth

DateTime features can also be used to calculate age.

A common approach is:

Age = Current Date - Date of Birth

For precise age calculations, the year/month/day relationship should be considered rather than simply dividing days by 365.

In [55]:
import pandas as pd

today = pd.Timestamp("2026-08-13")

df_age = pd.DataFrame({
    "Date_of_Birth": pd.to_datetime([
        "2000-05-10",
        "1995-08-20",
        "2005-01-15"
    ])
})

df_age["Age"] = (
    today.year - df_age["Date_of_Birth"].dt.year
    - (
        (df_age["Date_of_Birth"].dt.month > today.month)
        |
        (
            (df_age["Date_of_Birth"].dt.month == today.month)
            &
            (df_age["Date_of_Birth"].dt.day > today.day)
        )
    ).astype(int)
)

df_age

  Date_of_Birth  Age
0    2000-05-10   26
1    1995-08-20   30
2    2005-01-15   21

## Cyclical DateTime Features

Some datetime features are cyclical.

For example:

Hour 23 → Hour 0

These values are actually close together, but a normal numerical representation makes them appear far apart.

We can represent cyclical features using:

sin()

and

cos()

This is useful for:

- Hour
- Day of week
- Month
- Day of year

In [56]:
import numpy as np

df["Hour_Sin"] = np.sin(
    2 * np.pi * df["Hour"] / 24
)

df["Hour_Cos"] = np.cos(
    2 * np.pi * df["Hour"] / 24
)

df

,Date,Year,Month,Day,Day_of_Week,Day_Name,Is_Weekend,Hour,Minute,Second,Quarter,Week_of_Year,Day_of_Year,Time_of_Day,Month_Name,Month_Start,Month_End,Hour_Sin,Hour_Cos
0,2026-01-15 08:30:00,2026,1,15,3,Thursday,0,8,30,0,1,3,15,Morning,January,False,False,0.866025,-5.000000e-01
1,2026-02-20 14:45:00,2026,2,20,4,Friday,0,14,45,0,1,8,51,Afternoon,February,False,False,-0.500000,-8.660254e-01
2,2026-03-25 18:15:00,2026,3,25,2,Wednesday,0,18,15,0,1,13,84,Evening,March,False,False,-1.000000,-1.836970e-16
3,2026-04-10 21:00:00,2026,4,10,4,Friday,0,21,0,0,2,15,100,Night,April,False,False,-0.707107,7.071068e-01
4,2026-05-05 10:20:00,2026,5,5,1,Tuesday,0,10,20,0,2,19,125,Morning,May,False,False,0.500000,-8.660254e-01

In [57]:
datetime_features = pd.DataFrame({
    "Year": df["Date"].dt.year,
    "Month": df["Date"].dt.month,
    "Day": df["Date"].dt.day,
    "Day_of_Week": df["Date"].dt.dayofweek,
    "Hour": df["Date"].dt.hour,
    "Minute": df["Date"].dt.minute,
    "Quarter": df["Date"].dt.quarter,
    "Week_of_Year": df["Date"].dt.isocalendar().week,
    "Day_of_Year": df["Date"].dt.dayofyear,
    "Is_Weekend": (
        df["Date"].dt.dayofweek >= 5
    ).astype(int)
})

datetime_features

,Year,Month,Day,Day_of_Week,Hour,Minute,Quarter,Week_of_Year,Day_of_Year,Is_Weekend
0,2026,1,15,3,8,30,1,3,15,0
1,2026,2,20,4,14,45,1,8,51,0
2,2026,3,25,2,18,15,1,13,84,0
3,2026,4,10,4,21,0,2,15,100,0
4,2026,5,5,1,10,20,2,19,125,0