# Binning

Binning is a feature engineering technique that converts continuous numerical values into a smaller number of groups or intervals called **bins**.

Instead of using exact numerical values, we group similar values together.

For example:

Age:

0–18   → Child
19–35  → Young Adult
36–60  → Adult
61+    → Senior

Binning can simplify numerical data and make patterns easier for a machine learning model to learn.

## Why Do We Use Binning?

Binning can be useful when:

- A numerical feature has a non-linear relationship with the target.
- We want to reduce the effect of small variations.
- We want to convert continuous values into meaningful groups.
- We want to make numerical data easier to interpret.

Examples:

- Age groups
- Income groups
- Temperature ranges
- Exam score categories
- Customer spending groups

In [1]:
import pandas as pd

df = pd.DataFrame({
    "Age": [5, 12, 18, 22, 27, 35, 42, 50, 65, 80]
})

df

   Age
0    5
1   12
2   18
3   22
4   27
5   35
6   42
7   50
8   65
9   80

## Equal-Width Binning

Equal-width binning divides the range of values into intervals having approximately equal numerical widths.

For example:

0–20
20–40
40–60
60–80
80–100

Each interval has the same width.

In [2]:
df["Age_Bin"] = pd.cut(
    df["Age"],
    bins=4
)

df

   Age         Age_Bin
0    5  (4.925, 23.75]
1   12  (4.925, 23.75]
2   18  (4.925, 23.75]
3   22  (4.925, 23.75]
4   27   (23.75, 42.5]
5   35   (23.75, 42.5]
6   42   (23.75, 42.5]
7   50   (42.5, 61.25]
8   65   (61.25, 80.0]
9   80   (61.25, 80.0]

## Custom Binning

We can manually define meaningful boundaries based on domain knowledge.

For example:

- 0–18 → Child
- 19–35 → Young Adult
- 36–60 → Adult
- 61+ → Senior

In [3]:
bins = [0, 18, 35, 60, 100]

labels = [
    "Child",
    "Young Adult",
    "Adult",
    "Senior"
]

df["Age_Group"] = pd.cut(
    df["Age"],
    bins=bins,
    labels=labels,
    include_lowest=True
)

df

   Age         Age_Bin    Age_Group
0    5  (4.925, 23.75]        Child
1   12  (4.925, 23.75]        Child
2   18  (4.925, 23.75]        Child
3   22  (4.925, 23.75]  Young Adult
4   27   (23.75, 42.5]  Young Adult
5   35   (23.75, 42.5]  Young Adult
6   42   (23.75, 42.5]        Adult
7   50   (42.5, 61.25]        Adult
8   65   (61.25, 80.0]       Senior
9   80   (61.25, 80.0]       Senior

## Equal-Frequency Binning

Equal-frequency binning attempts to place approximately the same number of observations into each bin.

Pandas provides `qcut()` for this purpose.

It divides the data according to quantiles.

In [4]:
df["Age_Quantile_Bin"] = pd.qcut(
    df["Age"],
    q=4
)

df

   Age         Age_Bin    Age_Group Age_Quantile_Bin
0    5  (4.925, 23.75]        Child    (4.999, 19.0]
1   12  (4.925, 23.75]        Child    (4.999, 19.0]
2   18  (4.925, 23.75]        Child    (4.999, 19.0]
3   22  (4.925, 23.75]  Young Adult     (19.0, 31.0]
4   27   (23.75, 42.5]  Young Adult     (19.0, 31.0]
5   35   (23.75, 42.5]  Young Adult     (31.0, 48.0]
6   42   (23.75, 42.5]        Adult     (31.0, 48.0]
7   50   (42.5, 61.25]        Adult     (48.0, 80.0]
8   65   (61.25, 80.0]       Senior     (48.0, 80.0]
9   80   (61.25, 80.0]       Senior     (48.0, 80.0]

In [5]:
df["Age_Quantile_Group"] = pd.qcut(
    df["Age"],
    q=4,
    labels=[
        "Q1",
        "Q2",
        "Q3",
        "Q4"
    ]
)

df

   Age         Age_Bin    Age_Group Age_Quantile_Bin Age_Quantile_Group
0    5  (4.925, 23.75]        Child    (4.999, 19.0]                 Q1
1   12  (4.925, 23.75]        Child    (4.999, 19.0]                 Q1
2   18  (4.925, 23.75]        Child    (4.999, 19.0]                 Q1
3   22  (4.925, 23.75]  Young Adult     (19.0, 31.0]                 Q2
4   27   (23.75, 42.5]  Young Adult     (19.0, 31.0]                 Q2
5   35   (23.75, 42.5]  Young Adult     (31.0, 48.0]                 Q3
6   42   (23.75, 42.5]        Adult     (31.0, 48.0]                 Q3
7   50   (42.5, 61.25]        Adult     (48.0, 80.0]                 Q4
8   65   (61.25, 80.0]       Senior     (48.0, 80.0]                 Q4
9   80   (61.25, 80.0]       Senior     (48.0, 80.0]                 Q4

## Example: Exam Score Binning

Binning can convert numerical exam scores into meaningful performance categories.

Example:

0–49   → Fail
50–59  → Pass
60–69  → Good
70–79  → Very Good
80–100 → Excellent

In [6]:
df_scores = pd.DataFrame({
    "Score": [35, 48, 55, 62, 68, 73, 81, 90, 96]
})

bins = [0, 49, 59, 69, 79, 100]

labels = [
    "Fail",
    "Pass",
    "Good",
    "Very Good",
    "Excellent"
]

df_scores["Performance"] = pd.cut(
    df_scores["Score"],
    bins=bins,
    labels=labels,
    include_lowest=True
)

df_scores

   Score Performance
0     35        Fail
1     48        Fail
2     55        Pass
3     62        Good
4     68        Good
5     73   Very Good
6     81   Excellent
7     90   Excellent
8     96   Excellent

## Example: Income Binning

Income can also be converted into meaningful groups.

For example:

Low Income
Middle Income
High Income
Very High Income

The boundaries should be selected according to the dataset and domain.

In [7]:
df_income = pd.DataFrame({
    "Income": [
        20000,
        30000,
        50000,
        75000,
        100000,
        150000,
        250000
    ]
})

bins = [
    0,
    40000,
    80000,
    150000,
    float("inf")
]

labels = [
    "Low",
    "Middle",
    "High",
    "Very High"
]

df_income["Income_Group"] = pd.cut(
    df_income["Income"],
    bins=bins,
    labels=labels,
    include_lowest=True
)

df_income

   Income Income_Group
0   20000          Low
1   30000          Low
2   50000       Middle
3   75000       Middle
4  100000         High
5  150000         High
6  250000    Very High

## Converting Bins to Numerical Values

Some machine learning algorithms require numerical input.

Therefore, categorical bins can be converted into numerical labels.

For example:

Low → 0
Medium → 1
High → 2

In [8]:
df_income["Income_Group_Code"] = (
    df_income["Income_Group"]
    .cat.codes
)

df_income

   Income Income_Group  Income_Group_Code
0   20000          Low                  0
1   30000          Low                  0
2   50000       Middle                  1
3   75000       Middle                  1
4  100000         High                  2
5  150000         High                  2
6  250000    Very High                  3