# Mean, Median & Mode Imputation

Imputation is the process of replacing missing values with suitable values.

Three simple and commonly used imputation techniques are:

- Mean Imputation
- Median Imputation
- Mode Imputation

The choice depends on the type and distribution of the feature.

In [1]:
import pandas as pd
import numpy as np

df = pd.DataFrame({
    "Age": [20, 25, np.nan, 30, 35, np.nan, 40],
    "Salary": [30000, 45000, 50000, np.nan, 70000, 80000, np.nan],
    "City": ["Lahore", "Karachi", "Lahore", np.nan, "Islamabad", "Lahore", "Karachi"]
})

df

    Age   Salary       City
0  20.0  30000.0     Lahore
1  25.0  45000.0    Karachi
2   NaN  50000.0     Lahore
3  30.0      NaN        NaN
4  35.0  70000.0  Islamabad
5   NaN  80000.0     Lahore
6  40.0      NaN    Karachi

#### Identifying Missing Values

Before applying imputation, we first need to identify which columns contain missing values.

In [2]:
df.isnull().sum()

Age       2
Salary    2
City      1
dtype: int64

#### 1. Mean Imputation

Mean imputation replaces missing numerical values with the average of the available values.

### Formula

Mean = Sum of all values / Number of values

Mean imputation is generally suitable when:

- The feature is numerical.
- The data is approximately normally distributed.
- There are no significant outliers.

Mean imputation can be strongly affected by extreme values.

In [3]:
df_mean = df.copy()

mean_age = df_mean["Age"].mean()

df_mean["Age"] = df_mean["Age"].fillna(mean_age)

df_mean

    Age   Salary       City
0  20.0  30000.0     Lahore
1  25.0  45000.0    Karachi
2  30.0  50000.0     Lahore
3  30.0      NaN        NaN
4  35.0  70000.0  Islamabad
5  30.0  80000.0     Lahore
6  40.0      NaN    Karachi

In [4]:
df_mean["Age"].isnull().sum()

np.int64(0)

#### 2. Median Imputation

Median imputation replaces missing numerical values with the median of the available values.

The median is the middle value after sorting the data.

Median imputation is generally useful when:

- The feature is numerical.
- The data is skewed.
- The feature contains outliers.

The median is less affected by extreme values than the mean.

In [5]:
df_median = df.copy()

median_salary = df_median["Salary"].median()

df_median["Salary"] = df_median["Salary"].fillna(median_salary)

df_median

    Age   Salary       City
0  20.0  30000.0     Lahore
1  25.0  45000.0    Karachi
2   NaN  50000.0     Lahore
3  30.0  50000.0        NaN
4  35.0  70000.0  Islamabad
5   NaN  80000.0     Lahore
6  40.0  50000.0    Karachi

In [6]:
df_median["Salary"].isnull().sum()

np.int64(0)

In [7]:
print("Mean Salary:", df["Salary"].mean())
print("Median Salary:", df["Salary"].median())

Mean Salary: 55000.0
Median Salary: 50000.0

#### 3. Mode Imputation

Mode imputation replaces missing values with the most frequently occurring value.

Mode imputation is commonly used for categorical features.

For example, if:

Lahore → 3 times  
Karachi → 2 times  
Islamabad → 1 time

then the mode is `Lahore`.

In [8]:
df_mode = df.copy()

mode_city = df_mode["City"].mode()[0]

df_mode["City"] = df_mode["City"].fillna(mode_city)

df_mode

    Age   Salary       City
0  20.0  30000.0     Lahore
1  25.0  45000.0    Karachi
2   NaN  50000.0     Lahore
3  30.0      NaN     Lahore
4  35.0  70000.0  Islamabad
5   NaN  80000.0     Lahore
6  40.0      NaN    Karachi

In [9]:
df_mode["City"].isnull().sum()

np.int64(0)

#### Using Scikit-Learn SimpleImputer

Scikit-learn provides `SimpleImputer` for applying basic imputation strategies.

Available strategies include:

- `mean`
- `median`
- `most_frequent`
- `constant`

Using `SimpleImputer` is especially useful when building machine learning preprocessing pipelines.

In [10]:
from sklearn.impute import SimpleImputer

In [11]:
mean_imputer = SimpleImputer(strategy="mean")

df["Age"] = mean_imputer.fit_transform(
    df[["Age"]]
).ravel()

df

    Age   Salary       City
0  20.0  30000.0     Lahore
1  25.0  45000.0    Karachi
2  30.0  50000.0     Lahore
3  30.0      NaN        NaN
4  35.0  70000.0  Islamabad
5  30.0  80000.0     Lahore
6  40.0      NaN    Karachi

In [12]:
median_imputer = SimpleImputer(strategy="median")

df["Salary"] = median_imputer.fit_transform(
    df[["Salary"]]
).ravel()

df

    Age   Salary       City
0  20.0  30000.0     Lahore
1  25.0  45000.0    Karachi
2  30.0  50000.0     Lahore
3  30.0  50000.0        NaN
4  35.0  70000.0  Islamabad
5  30.0  80000.0     Lahore
6  40.0  50000.0    Karachi

In [13]:
mode_imputer = SimpleImputer(strategy="most_frequent")

df["City"] = mode_imputer.fit_transform(
    df[["City"]]
).ravel()

df

    Age   Salary       City
0  20.0  30000.0     Lahore
1  25.0  45000.0    Karachi
2  30.0  50000.0     Lahore
3  30.0  50000.0     Lahore
4  35.0  70000.0  Islamabad
5  30.0  80000.0     Lahore
6  40.0  50000.0    Karachi