### Forward Fill & Backward Fill

Forward Fill and Backward Fill are techniques used to replace missing values using nearby observations.

- **Forward Fill (ffill):** Uses the previous available value.
- **Backward Fill (bfill):** Uses the next available value.

These techniques are especially useful for ordered or time-series data.

In [1]:
import pandas as pd
import numpy as np

df = pd.DataFrame({
    "Day": [1, 2, 3, 4, 5, 6, 7],
    "Temperature": [30, np.nan, np.nan, 34, np.nan, 36, np.nan],
    "Sales": [100, 120, np.nan, np.nan, 180, np.nan, 220]
})

df

   Day  Temperature  Sales
0    1         30.0  100.0
1    2          NaN  120.0
2    3          NaN    NaN
3    4         34.0    NaN
4    5          NaN  180.0
5    6         36.0    NaN
6    7          NaN  220.0

#### Identifying Missing Values

Before filling missing values, we first check which columns contain missing observations.

In [2]:
df.isnull().sum()

Day            0
Temperature    4
Sales          3
dtype: int64

#### 1. Forward Fill

Forward Fill (`ffill`) replaces a missing value with the most recent available value before it.

For example:

Before:

10  
20  
NaN  
NaN  
50

After Forward Fill:

10  
20  
20  
20  
50

Forward Fill is useful when the previous observation is a reasonable estimate of the missing value.

In [3]:
df_ffill = df.copy()

df_ffill["Temperature"] = df_ffill["Temperature"].ffill()

df_ffill

   Day  Temperature  Sales
0    1         30.0  100.0
1    2         30.0  120.0
2    3         30.0    NaN
3    4         34.0    NaN
4    5         34.0  180.0
5    6         36.0    NaN
6    7         36.0  220.0

In [4]:
df_ffill = df.copy()

df_ffill["Sales"] = df_ffill["Sales"].ffill()

df_ffill

   Day  Temperature  Sales
0    1         30.0  100.0
1    2          NaN  120.0
2    3          NaN  120.0
3    4         34.0  120.0
4    5          NaN  180.0
5    6         36.0  180.0
6    7          NaN  220.0

#### 2. Backward Fill

Backward Fill (`bfill`) replaces a missing value with the next available value after it.

For example:

Before:

10  
20  
NaN  
NaN  
50

After Backward Fill:

10  
20  
50  
50  
50

Backward Fill is useful when the next observation is a reasonable estimate of the missing value.

In [5]:
df_bfill = df.copy()

df_bfill["Temperature"] = df_bfill["Temperature"].bfill()

df_bfill

   Day  Temperature  Sales
0    1         30.0  100.0
1    2         34.0  120.0
2    3         34.0    NaN
3    4         34.0    NaN
4    5         36.0  180.0
5    6         36.0    NaN
6    7          NaN  220.0

In [6]:
df_bfill = df.copy()

df_bfill["Sales"] = df_bfill["Sales"].bfill()

df_bfill

   Day  Temperature  Sales
0    1         30.0  100.0
1    2          NaN  120.0
2    3          NaN  180.0
3    4         34.0  180.0
4    5          NaN  180.0
5    6         36.0  220.0
6    7          NaN  220.0

#### Forward Fill with Time-Series Data

Forward Fill is commonly used with time-series data because observations are naturally ordered by time.

For example, suppose a sensor records temperature throughout the day, but some readings are missing.

In [7]:
dates = pd.date_range(
    start="2026-01-01",
    periods=7,
    freq="D"
)

temperature_df = pd.DataFrame({
    "Date": dates,
    "Temperature": [30, 31, np.nan, np.nan, 34, np.nan, 36]
})

temperature_df

        Date  Temperature
0 2026-01-01         30.0
1 2026-01-02         31.0
2 2026-01-03          NaN
3 2026-01-04          NaN
4 2026-01-05         34.0
5 2026-01-06          NaN
6 2026-01-07         36.0

In [8]:
temperature_df["Temperature"] = (
    temperature_df["Temperature"].ffill()
)

temperature_df

        Date  Temperature
0 2026-01-01         30.0
1 2026-01-02         31.0
2 2026-01-03         31.0
3 2026-01-04         31.0
4 2026-01-05         34.0
5 2026-01-06         34.0
6 2026-01-07         36.0

In [9]:
temperature_df = pd.DataFrame({
    "Date": dates,
    "Temperature": [30, 31, np.nan, np.nan, 34, np.nan, 36]
})

temperature_df["Temperature"] = (
    temperature_df["Temperature"].bfill()
)

temperature_df

        Date  Temperature
0 2026-01-01         30.0
1 2026-01-02         31.0
2 2026-01-03         34.0
3 2026-01-04         34.0
4 2026-01-05         34.0
5 2026-01-06         36.0
6 2026-01-07         36.0

#### Important Limitations

Forward Fill and Backward Fill should not be used blindly.

Potential problems include:

- A value may remain unchanged for too long.
- Large gaps can produce unrealistic values.
- The method may not be appropriate for every dataset.
- The order of observations is important.
- Forward Fill cannot fill missing values at the beginning if no previous value exists.
- Backward Fill cannot fill missing values at the end if no next value exists.

Always consider the meaning and structure of the data before choosing an imputation method.