# KNN Imputation

KNN (K-Nearest Neighbors) Imputation is a missing-value technique that uses similar observations to estimate missing values.

Instead of replacing a missing value with a single statistic such as the mean or median, KNN Imputation looks at the nearest observations and uses their values to calculate the replacement.

The similarity between observations is usually determined using a distance metric such as Euclidean distance.

## How Does KNN Imputation Work?

The basic process is:

1. Find observations with similar feature values.
2. Identify the `K` nearest observations.
3. Look at the values of the feature containing the missing value.
4. Calculate an appropriate value from those neighbors.
5. Replace the missing value.

For example, if `K = 3`, the algorithm uses the 3 nearest observations to estimate the missing value.

A smaller `K` considers fewer neighbors, while a larger `K` considers more neighbors.

In [1]:
import pandas as pd
import numpy as np

from sklearn.impute import KNNImputer

In [2]:
df = pd.DataFrame({
    "Age": [20, 22, 25, np.nan, 30, 32, 35],
    "Salary": [30000, 35000, np.nan, 50000, 55000, np.nan, 70000],
    "Experience": [1, 2, 3, 5, np.nan, 8, 10]
})

df

    Age   Salary  Experience
0  20.0  30000.0         1.0
1  22.0  35000.0         2.0
2  25.0      NaN         3.0
3   NaN  50000.0         5.0
4  30.0  55000.0         NaN
5  32.0      NaN         8.0
6  35.0  70000.0        10.0

In [3]:
df.isnull().sum()

Age           1
Salary        2
Experience    1
dtype: int64

#### Applying KNN Imputation

Scikit-learn provides the `KNNImputer` class for KNN-based missing-value imputation.

The `n_neighbors` parameter determines how many neighboring observations are used.

For example:

`n_neighbors=3`

means the algorithm considers the 3 nearest observations.

In [4]:
imputer = KNNImputer(n_neighbors=3)

df_imputed = pd.DataFrame(
    imputer.fit_transform(df),
    columns=df.columns
)

df_imputed

    Age        Salary  Experience
0  20.0  30000.000000    1.000000
1  22.0  35000.000000    2.000000
2  25.0  38333.333333    3.000000
3  29.0  50000.000000    5.000000
4  30.0  55000.000000    5.333333
5  32.0  58333.333333    8.000000
6  35.0  70000.000000   10.000000

#### Before vs After Imputation

Let's compare the original dataset with the dataset after KNN imputation.

In [5]:
print("Original Dataset:")
display(df)

print("\nKNN Imputed Dataset:")
display(df_imputed)

Original Dataset:

    Age   Salary  Experience
0  20.0  30000.0         1.0
1  22.0  35000.0         2.0
2  25.0      NaN         3.0
3   NaN  50000.0         5.0
4  30.0  55000.0         NaN
5  32.0      NaN         8.0
6  35.0  70000.0        10.0

KNN Imputed Dataset:

    Age        Salary  Experience
0  20.0  30000.000000    1.000000
1  22.0  35000.000000    2.000000
2  25.0  38333.333333    3.000000
3  29.0  50000.000000    5.000000
4  30.0  55000.000000    5.333333
5  32.0  58333.333333    8.000000
6  35.0  70000.000000   10.000000

In [6]:
df_imputed.isnull().sum()

Age           0
Salary        0
Experience    0
dtype: int64