# Iterative Imputation

Iterative Imputation is an advanced technique for handling missing values.

Instead of replacing missing values using only the mean or median, Iterative Imputation uses relationships between features to estimate missing values.

The process works iteratively:

1. Initialize missing values with an initial estimate.
2. Select one feature containing missing values.
3. Use the other features to predict its missing values.
4. Replace the missing values with the predictions.
5. Repeat the process for other features.
6. Continue for several iterations until the estimates become stable.

Iterative Imputation is also known as **Multivariate Imputation**.

#### How Does Iterative Imputation Work?

Suppose we have:

- Age
- Salary
- Experience

If Salary is missing, we can use Age and Experience to estimate Salary.

If Age is missing, we can use Salary and Experience to estimate Age.

The algorithm repeatedly updates these estimates using relationships between the features.

This makes Iterative Imputation different from simple imputation methods such as mean and median imputation.

In [1]:
import pandas as pd
import numpy as np

from sklearn.experimental import enable_iterative_imputer
from sklearn.impute import IterativeImputer

In [2]:
df = pd.DataFrame({
    "Age": [20, 22, np.nan, 28, 30, np.nan, 35],
    "Salary": [30000, np.nan, 42000, 50000, np.nan, 65000, 70000],
    "Experience": [1, 2, 3, np.nan, 6, 8, 10]
})

df

    Age   Salary  Experience
0  20.0  30000.0         1.0
1  22.0      NaN         2.0
2   NaN  42000.0         3.0
3  28.0  50000.0         NaN
4  30.0      NaN         6.0
5   NaN  65000.0         8.0
6  35.0  70000.0        10.0

In [3]:
df.isnull().sum()

Age           2
Salary        2
Experience    1
dtype: int64

#### Applying Iterative Imputation

Scikit-learn provides `IterativeImputer` for multivariate iterative imputation.

By default, it uses a Bayesian Ridge regression model to estimate missing values.

The estimator can also be changed to another machine learning model.

In [4]:
imputer = IterativeImputer(
    random_state=42
)

df_imputed = pd.DataFrame(
    imputer.fit_transform(df),
    columns=df.columns
)

df_imputed

         Age        Salary  Experience
0  20.000000  30000.000000    1.000000
1  22.000000  35095.623389    2.000000
2  24.668320  42000.000000    3.000000
3  28.000000  50000.000000    5.075511
4  30.000000  55785.093760    6.000000
5  33.342986  65000.000000    8.000000
6  35.000000  70000.000000   10.000000

In [5]:
print("Original Dataset:")
display(df)

print("\nIteratively Imputed Dataset:")
display(df_imputed)

Original Dataset:

    Age   Salary  Experience
0  20.0  30000.0         1.0
1  22.0      NaN         2.0
2   NaN  42000.0         3.0
3  28.0  50000.0         NaN
4  30.0      NaN         6.0
5   NaN  65000.0         8.0
6  35.0  70000.0        10.0

Iteratively Imputed Dataset:

         Age        Salary  Experience
0  20.000000  30000.000000    1.000000
1  22.000000  35095.623389    2.000000
2  24.668320  42000.000000    3.000000
3  28.000000  50000.000000    5.075511
4  30.000000  55785.093760    6.000000
5  33.342986  65000.000000    8.000000
6  35.000000  70000.000000   10.000000

In [6]:
df_imputed.isnull().sum()

Age           0
Salary        0
Experience    0
dtype: int64