# Bag of Words (BoW)

Bag of Words (BoW) is a text feature engineering technique that converts
text into numerical features based on the frequency of words.

It represents each document as a vector of word counts.

Bag of Words does not consider:

- Word order
- Grammar
- Meaning of words

It mainly focuses on:

- Which words are present
- How frequently each word occurs

In [1]:
documents = [
    "I love Python",
    "I love Machine Learning"
]

documents

['I love Python', 'I love Machine Learning']

## Creating the Vocabulary

The vocabulary contains all unique words present in the documents.

For example:

"I love Python"
"I love Machine Learning"

Vocabulary:

I
love
Python
Machine
Learning

## Bag of Words Using CountVectorizer

Scikit-learn provides `CountVectorizer` to create a Bag of Words
representation automatically.

It:

1. Tokenizes the text.
2. Creates a vocabulary.
3. Counts word occurrences.
4. Converts documents into numerical vectors.

In [2]:
from sklearn.feature_extraction.text import CountVectorizer

vectorizer = CountVectorizer()

X = vectorizer.fit_transform(documents)

X

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 5 stored elements and shape (2, 4)>

In [3]:
X.toarray()

array([[0, 1, 0, 1],
       [1, 1, 1, 0]])

In [4]:
vectorizer.get_feature_names_out()

array(['learning', 'love', 'machine', 'python'], dtype=object)

## Understanding the Bag of Words Matrix

Each row represents one document.

Each column represents one word in the vocabulary.

The values represent how many times that word appears in the document.

For example:

Document 1:
"I love Python"

Document 2:
"I love Machine Learning"

The matrix contains the frequency of each vocabulary word
for each document.

In [5]:
documents = [
    "python is easy",
    "python is powerful",
    "python python is popular"
]

vectorizer = CountVectorizer()

X = vectorizer.fit_transform(documents)

print(vectorizer.get_feature_names_out())
print(X.toarray())

['easy' 'is' 'popular' 'powerful' 'python']
[[1 1 0 0 1]
 [0 1 0 1 1]
 [0 1 1 0 2]]

## Word Frequency

Bag of Words counts how many times each word occurs in a document.

For example:

"python python machine"

Vocabulary:

machine
python

Vector:

[1, 2]

The word "python" appears twice.
The word "machine" appears once.

## Lowercase Handling

By default, `CountVectorizer` converts text to lowercase.

Therefore:

"Python"

and

"python"

are treated as the same word.

In [6]:
documents = [
    "Python is powerful",
    "python is easy"
]

vectorizer = CountVectorizer()

X = vectorizer.fit_transform(documents)

print(vectorizer.get_feature_names_out())
print(X.toarray())

['easy' 'is' 'powerful' 'python']
[[0 1 1 1]
 [1 1 0 1]]

## Removing Stop Words

Stop words are common words that may provide little useful information
for some machine learning tasks.

Examples:

- the
- is
- a
- an
- and
- of

`CountVectorizer` can remove English stop words using:

`stop_words="english"`

In [7]:
documents = [
    "Python is a powerful programming language",
    "Python is easy to learn"
]

vectorizer = CountVectorizer(
    stop_words="english"
)

X = vectorizer.fit_transform(documents)

print(vectorizer.get_feature_names_out())
print(X.toarray())

['easy' 'language' 'learn' 'powerful' 'programming' 'python']
[[0 1 0 1 1 1]
 [1 0 1 0 0 1]]

## Binary Bag of Words

Instead of counting how many times a word occurs, we can represent whether
the word exists or not.

Presence of word:

1 → Present

0 → Not Present

This can be useful when word frequency is less important than word presence.

In [8]:
documents = [
    "python python machine",
    "python data science"
]

vectorizer = CountVectorizer(
    binary=True
)

X = vectorizer.fit_transform(documents)

print(vectorizer.get_feature_names_out())
print(X.toarray())

['data' 'machine' 'python' 'science']
[[0 1 1 0]
 [1 0 1 1]]

## N-Grams with Bag of Words

Normal Bag of Words uses individual words, called unigrams.

Example:

"machine learning"

Unigrams:

machine
learning

We can also capture combinations of words.

Bigram:

machine learning

N-grams can help preserve some information about word order.

In [9]:
documents = [
    "machine learning is powerful",
    "deep learning is useful"
]

vectorizer = CountVectorizer(
    ngram_range=(1, 2)
)

X = vectorizer.fit_transform(documents)

print(vectorizer.get_feature_names_out())

['deep' 'deep learning' 'is' 'is powerful' 'is useful' 'learning'
 'learning is' 'machine' 'machine learning' 'powerful' 'useful']

In [10]:
import pandas as pd

df = pd.DataFrame({
    "Text": [
        "I love machine learning",
        "Python is great for machine learning",
        "I love Python",
        "Machine learning is powerful"
    ]
})

df

                                   Text
0               I love machine learning
1  Python is great for machine learning
2                         I love Python
3          Machine learning is powerful

In [11]:
vectorizer = CountVectorizer()

X = vectorizer.fit_transform(df["Text"])

X_array = X.toarray()

X_array

array([[0, 0, 0, 1, 1, 1, 0, 0],
       [1, 1, 1, 1, 0, 1, 0, 1],
       [0, 0, 0, 0, 1, 0, 0, 1],
       [0, 0, 1, 1, 0, 1, 1, 0]])

In [12]:
bow_df = pd.DataFrame(
    X_array,
    columns=vectorizer.get_feature_names_out()
)

bow_df

   for  great  is  learning  love  machine  powerful  python
0    0      0   0         1     1        1         0       0
1    1      1   1         1     0        1         0       1
2    0      0   0         0     1        0         0       1
3    0      0   1         1     0        1         1       0

## Sparse Matrix

Bag of Words usually produces a sparse matrix.

A sparse matrix contains many zero values because each document usually
contains only a small portion of the complete vocabulary.

Scikit-learn therefore stores the result efficiently as a sparse matrix.

Use:

`X.toarray()`

only when you want to inspect the matrix.

For large datasets, converting the entire matrix to an array can consume
a large amount of memory.