# Feature Types

Feature types describe the kind of information stored in a dataset's columns.

Understanding feature types is an important step in data preprocessing and feature engineering because different types of features require different preprocessing techniques.

For example:

- Numerical features may require scaling.
- Categorical features may require encoding.
- Date-time features can be transformed into useful components.
- Text features can be converted into numerical representations.

#### 1. Numerical Features

Numerical features contain numbers and represent measurable quantities.

Examples:

- Age
- Salary
- Height
- Weight
- House Price
- Number of Rooms

Numerical features are mainly divided into two types:

1. Discrete Features
2. Continuous Features

In [1]:
import pandas as pd
import numpy as np

df = pd.DataFrame({
    "age": [19, 22, 25, 30, 35],
    "salary": [30000, 45000, 55000, 70000, 85000],
    "height": [165.5, 172.3, 180.2, 168.7, 175.4]
})

df

   age  salary  height
0   19   30000   165.5
1   22   45000   172.3
2   25   55000   180.2
3   30   70000   168.7
4   35   85000   175.4

#### 2. Discrete Features

Discrete features contain countable numerical values.

Examples:
- Number of children
- Number of bedrooms
- Number of employees
- Number of products

Discrete values are usually whole numbers.

In [2]:
df = pd.DataFrame({
    "number_of_bedrooms": [1, 2, 3, 4, 5],
    "number_of_children": [0, 1, 2, 3, 4],
    "number_of_products": [2, 5, 3, 8, 10]
})

df

   number_of_bedrooms  number_of_children  number_of_products
0                   1                   0                   2
1                   2                   1                   5
2                   3                   2                   3
3                   4                   3                   8
4                   5                   4                  10

#### 3. Continuous Features

Continuous features can take any numerical value within a range.

Examples:
- Height
- Weight
- Temperature
- Distance
- Salary

Continuous features usually represent measurements.

In [3]:
df = pd.DataFrame({
    "height": [165.5, 172.3, 180.7, 168.9, 175.4],
    "weight": [60.5, 68.7, 82.4, 64.8, 75.2],
    "temperature": [36.5, 37.2, 36.8, 37.0, 36.6]
})

df

   height  weight  temperature
0   165.5    60.5         36.5
1   172.3    68.7         37.2
2   180.7    82.4         36.8
3   168.9    64.8         37.0
4   175.4    75.2         36.6

#### 4. Categorical Features

Categorical features represent groups or categories rather than measurable quantities.

Examples:
- Gender
- City
- Department
- Product Category
- Education Level

Categorical features are mainly divided into:
- Nominal
- Ordinal

In [4]:
df = pd.DataFrame({
    "city": ["Lahore", "Karachi", "Islamabad", "Lahore"],
    "department": ["IT", "HR", "Finance", "IT"],
    "category": ["A", "B", "A", "C"]
})

df

        city department category
0     Lahore         IT        A
1    Karachi         HR        B
2  Islamabad    Finance        A
3     Lahore         IT        C

#### 5. Nominal Features

Nominal features contain categories that do not have a meaningful order or ranking.

Examples:
- City
- Country
- Eye Color
- Blood Group
- Product Category

Example:

Lahore, Karachi, Islamabad

There is no natural order between these categories.

In [5]:
df = pd.DataFrame({
    "city": ["Lahore", "Karachi", "Islamabad", "Lahore"],
    "blood_group": ["A+", "B+", "O+", "AB+"]
})

df

        city blood_group
0     Lahore          A+
1    Karachi          B+
2  Islamabad          O+
3     Lahore         AB+

#### 6. Ordinal Features

Ordinal features contain categories with a meaningful order or ranking.

Examples:
- Education Level
- Satisfaction Level
- Product Size
- Rating

Example:

Small < Medium < Large

The order contains useful information.

In [6]:
df = pd.DataFrame({
    "size": ["Small", "Medium", "Large", "Medium"],
    "satisfaction": ["Low", "Medium", "High", "High"]
})

df

     size satisfaction
0   Small          Low
1  Medium       Medium
2   Large         High
3  Medium         High

#### 7. Binary Features

Binary features contain only two possible values.

Examples:
- Yes / No
- True / False
- 0 / 1
- Spam / Not Spam
- Pass / Fail

In [7]:
df = pd.DataFrame({
    "is_student": [1, 0, 1, 1, 0],
    "is_employed": [True, False, True, True, False],
    "is_spam": ["Yes", "No", "No", "Yes", "No"]
})

df

   is_student  is_employed is_spam
0           1         True     Yes
1           0        False      No
2           1         True      No
3           1         True     Yes
4           0        False      No

#### 8. Date & Time Features

Date and time features contain temporal information.

Examples:
- Date of Birth
- Purchase Date
- Order Date
- Login Time
- Transaction Time

Date and time features can be transformed into:
- Year
- Month
- Day
- Day of Week
- Hour
- Weekend/Weekday

In [8]:
df = pd.DataFrame({
    "purchase_date": [
        "2026-01-10",
        "2026-02-15",
        "2026-03-20",
        "2026-04-05"
    ]
})

df["purchase_date"] = pd.to_datetime(df["purchase_date"])

df

  purchase_date
0    2026-01-10
1    2026-02-15
2    2026-03-20
3    2026-04-05

In [9]:
df["year"] = df["purchase_date"].dt.year
df["month"] = df["purchase_date"].dt.month
df["day"] = df["purchase_date"].dt.day
df["day_of_week"] = df["purchase_date"].dt.day_name()

df

  purchase_date  year  month  day day_of_week
0    2026-01-10  2026      1   10    Saturday
1    2026-02-15  2026      2   15      Sunday
2    2026-03-20  2026      3   20      Friday
3    2026-04-05  2026      4    5      Sunday

#### 9. Text Features

Text features contain natural language.

Examples:
- Customer Reviews
- Emails
- Tweets
- Comments
- Product Descriptions

Raw text cannot usually be directly used by traditional machine learning models.

It can be converted into numerical features using:
- Bag of Words
- TF-IDF
- Word Embeddings
- Tokenization

In [10]:
df = pd.DataFrame({
    "review": [
        "This product is excellent",
        "Very good quality",
        "I did not like this product",
        "Amazing experience"
    ]
})

df

                        review
0    This product is excellent
1            Very good quality
2  I did not like this product
3           Amazing experience

#### 10. Target Feature

The target feature is the variable that a machine learning model tries to predict.

Examples:

House Price Prediction:
- Features → Area, Bedrooms, Location
- Target → Price

Spam Detection:
- Features → Email Text
- Target → Spam / Not Spam

In [11]:
df = pd.DataFrame({
    "age": [20, 25, 30, 35],
    "salary": [30000, 45000, 60000, 75000],
    "experience": [1, 3, 6, 10],
    "purchased": [0, 1, 1, 1]
})

X = df.drop("purchased", axis=1)
y = df["purchased"]

X

   age  salary  experience
0   20   30000           1
1   25   45000           3
2   30   60000           6
3   35   75000          10

In [12]:
y

0    0
1    1
2    1
3    1
Name: purchased, dtype: int64