### Data Cleaning

Data Cleaning is the process of identifying and correcting inaccurate, incomplete, duplicate, or inconsistent data within a dataset. It is one of the most critical steps in the Data Science workflow because the quality of the data directly impacts the accuracy of analysis and machine learning models.

Real-world datasets often contain missing values, duplicate records, incorrect data types, inconsistent formatting, and invalid entries. If these issues are not addressed, they can lead to misleading insights, poor model performance, and incorrect business decisions.

#### Importing required libraries for data cleaning

In [26]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

#### Load the Dataset

The Titanic dataset is one of the most widely used datasets for learning Data Science and Machine Learning. It contains information about passengers aboard the RMS Titanic, including demographic details, ticket information, travel class, fare, and survival status.

After loading the dataset, we display the first few rows to verify that the data has been loaded successfully.

In [27]:
# Load Titanic Dataset
df = sns.load_dataset("titanic")
# Display first five rows
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

#### Create a Copy of the Dataset

Before performing any cleaning operations, it is recommended to create a copy of the original dataset. This ensures that the original data remains unchanged and can be used for comparison or recovery if needed.

In [28]:
# Create a copy of the dataset
df = df.copy()
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

#### Check Missing Values

Missing values represent unavailable or unknown information within a dataset. They may occur due to human error, equipment failure, incomplete surveys, or data collection issues.

Identifying missing values is an essential step because they can affect statistical analysis and machine learning performance.

The `isnull()` function detects missing values, while the `sum()` function counts the number of missing values in each column.

In [29]:
# Check missing values
df.isnull().sum()

survived         0
pclass           0
sex              0
age            177
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64

####  Handle Missing Values

After identifying missing values, we need to decide how to handle them. Common approaches include:

- Removing rows containing missing values.
- Removing columns with excessive missing values.
- Filling missing values using the mean.
- Filling missing values using the median.
- Filling missing values using the mode.

The appropriate method depends on the nature of the dataset and the feature being cleaned.

In [30]:
# Fill missing Age values with the median
df["age"] = df["age"].fillna(df["age"].median())

# Fill missing Embarked values with the mode
df["embarked"] = df["embarked"].fillna(df["embarked"].mode()[0])

# Drop the Deck column because it contains many missing values
df.drop(columns="deck", inplace=True)

# Verify remaining missing values
df.isnull().sum()

survived       0
pclass         0
sex            0
age            0
sibsp          0
parch          0
fare           0
embarked       0
class          0
who            0
adult_male     0
embark_town    2
alive          0
alone          0
dtype: int64

#### Check Duplicate Records

Duplicate records occur when the same observation appears more than once in a dataset. These duplicates can distort statistical analysis and negatively affect machine learning models.

Before removing duplicates, it is important to determine how many duplicate rows exist.

In [31]:
# Count duplicate rows
df.duplicated().sum()

np.int64(116)

####  Remove Duplicate Records

If duplicate records are present, they should be removed to improve data quality and ensure that each observation represents unique information.

In [32]:
# Remove duplicate rows
df.drop_duplicates(inplace=True)

# Verify duplicates
df.duplicated().sum()

np.int64(0)

#### Check Data Types

Every column in a dataset has a specific data type, such as integer, float, object, boolean, or category.

Checking data types helps ensure that each feature is stored correctly and allows appropriate statistical operations to be performed.

In [33]:
# Display data types
df.dtypes

# More detailed information
df.info()

<class 'pandas.DataFrame'>
Index: 775 entries, 0 to 890
Data columns (total 14 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   survived     775 non-null    int64
 1   pclass       775 non-null    int64
 2   sex          775 non-null    str
 3   age          775 non-null    float64
 4   sibsp        775 non-null    int64
 5   parch        775 non-null    int64
 6   fare         775 non-null    float64
 7   embarked     775 non-null    str
 8   class        775 non-null    category
 9   who          775 non-null    str
 10  adult_male   775 non-null    bool
 11  embark_town  773 non-null    str
 12  alive        775 non-null    str
 13  alone        775 non-null    bool
dtypes: bool(2), category(1), float64(2), int64(4), str(5)
memory usage: 75.1 KB

####  Convert Data Types

Sometimes a feature is stored using an incorrect data type. Converting columns to the appropriate type improves memory efficiency and ensures accurate analysis.

In [34]:
# Convert Survived column to integer
df["survived"] = df["survived"].astype("int")

df.dtypes

survived          int64
pclass            int64
sex                 str
age             float64
sibsp             int64
parch             int64
fare            float64
embarked            str
class          category
who                 str
adult_male         bool
embark_town         str
alive               str
alone              bool
dtype: object

####  Rename Columns

Renaming columns improves readability and makes feature names more descriptive, especially when sharing notebooks or collaborating with others.

In [35]:
# Rename selected columns
df.rename(
    columns={
        "sibsp": "siblings_spouses",
        "parch": "parents_children"
    },
    inplace=True
)

df.columns

Index(['survived', 'pclass', 'sex', 'age', 'siblings_spouses',
       'parents_children', 'fare', 'embarked', 'class', 'who', 'adult_male',
       'embark_town', 'alive', 'alone'],
      dtype='str')

####  Handle Inconsistent Values

Text data may contain inconsistent formatting, such as extra spaces or different letter cases. Cleaning these values ensures consistency across the dataset.

In [36]:
# Remove extra spaces
df["sex"] = df["sex"].str.strip()

# Convert to lowercase
df["sex"] = df["sex"].str.lower()

# Display unique values
df["sex"].unique()

<StringArray>
['male', 'female']
Length: 2, dtype: str

#### Final Data Quality Check

After completing the cleaning process, a final inspection is performed to ensure that the dataset is free from major quality issues and is ready for Exploratory Data Analysis and Machine Learning.

In [37]:
# Dataset Information
df.info()

# Missing Values
print(df.isnull().sum())

# Duplicate Records
print(df.duplicated().sum())

# Display cleaned dataset
df.head()

<class 'pandas.DataFrame'>
Index: 775 entries, 0 to 890
Data columns (total 14 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   survived          775 non-null    int64
 1   pclass            775 non-null    int64
 2   sex               775 non-null    str
 3   age               775 non-null    float64
 4   siblings_spouses  775 non-null    int64
 5   parents_children  775 non-null    int64
 6   fare              775 non-null    float64
 7   embarked          775 non-null    str
 8   class             775 non-null    category
 9   who               775 non-null    str
 10  adult_male        775 non-null    bool
 11  embark_town       773 non-null    str
 12  alive             775 non-null    str
 13  alone             775 non-null    bool
dtypes: bool(2), category(1), float64(2), int64(4), str(5)
memory usage: 75.1 KB
survived            0
pclass              0
sex                 0
age                 0
siblings_spouses    0
parents_children    0
fare                0
embarked            0
class               0
who                 0
adult_male          0
embark_town         2
alive               0
alone               0
dtype: int64
0

,survived,pclass,sex,age,siblings_spouses,parents_children,fare,embarked,class,who,adult_male,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,Southampton,no,True

In [38]:
# Save the cleaned dataset as a CSV file
df.to_csv("clean_titanic.csv", index=False)
print("✅Clean Titanic dataset saved successfully!")

✅Clean Titanic dataset saved successfully!