# 🎬 IMDb Movie Review Sentiment Analysis

### Author
**Muhammad Anas**

---

## 📌 Project Overview

This project aims to classify movie reviews as **Positive** or **Negative** using Natural Language Processing (NLP) and Machine Learning techniques.

The project includes data preprocessing, exploratory data analysis (EDA), text feature extraction, model training, evaluation, and a prediction pipeline for new user reviews.

---

## 🎯 Project Objectives

- Load and understand the dataset.
- Perform Exploratory Data Analysis (EDA).
- Clean and preprocess the text data.
- Convert text into numerical features.
- Train and evaluate machine learning models.
- Build a prediction pipeline for new reviews.
- Predict whether a review is **Positive** or **Negative**.

---

## 🛠️ Tools & Libraries

- Python
- Pandas
- NumPy
- Matplotlib
- Seaborn
- NLTK
- BeautifulSoup
- Regular Expressions (re)
- Scikit-learn
- Gensim (Word2Vec)
- Pickle

---

## 📚 Project Workflow

1. Load Dataset
2. Exploratory Data Analysis (EDA)
3. Text Preprocessing
4. Feature Engineering
5. Train-Test Split
6. Model Training
7. Model Evaluation
8. Save the Model
9. Build Prediction Pipeline
10. Predict Sentiment of New Reviews

---

## 🎯 Expected Output

The final model will classify a movie review as:

- 😊 Positive
- 😞 Negative

### Importing the Libraries

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from wordcloud import WordCloud
import re
import string
from bs4 import BeautifulSoup
import nltk
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords
from nltk.stem import PorterStemmer
from nltk.stem import WordNetLemmatizer
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import MultinomialNB
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import (
    accuracy_score,
)
import warnings
warnings.filterwarnings("ignore")

### Load the data

In [2]:
data=pd.read_csv('D:\DATA_SCIENCE_PROJECTS\DATASETS\IMDB_Dataset.csv')
data.head(5)

                                              review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

In [3]:
#checking the shape of the data 
data.shape

(50000, 2)

In [4]:
#checking for the nulls values
data.isnull().sum()

review       0
sentiment    0
dtype: int64

In [5]:
#checking for the value counts of the sentiment
data['sentiment'].value_counts()

sentiment
positive    25000
negative    25000
Name: count, dtype: int64

### Text Preprocessing

In [6]:
#convering into x and y
X=data['review']
y=data['sentiment']

In [7]:
#checking the shape of x and y
X.shape,y.shape

((50000,), (50000,))

In [8]:
X[0]

"One of the other reviewers has mentioned that after watching just 1 Oz episode you'll be hooked. They are right, as this is exactly what happened with me.<br /><br />The first thing that struck me about Oz was its brutality and unflinching scenes of violence, which set in right from the word GO. Trust me, this is not a show for the faint hearted or timid. This show pulls no punches with regards to drugs, sex or violence. Its is hardcore, in the classic use of the word.<br /><br />It is called OZ as that is the nickname given to the Oswald Maximum Security State Penitentary. It focuses mainly on Emerald City, an experimental section of the prison where all the cells have glass fronts and face inwards, so privacy is not high on the agenda. Em City is home to many..Aryans, Muslims, gangstas, Latinos, Christians, Italians, Irish and more....so scuffles, death stares, dodgy dealings and shady agreements are never far away.<br /><br />I would say the main appeal of the show is due to the fact that it goes where other shows wouldn't dare. Forget pretty pictures painted for mainstream audiences, forget charm, forget romance...OZ doesn't mess around. The first episode I ever saw struck me as so nasty it was surreal, I couldn't say I was ready for it, but as I watched more, I developed a taste for Oz, and got accustomed to the high levels of graphic violence. Not just violence, but injustice (crooked guards who'll be sold out for a nickel, inmates who'll kill on order and get away with it, well mannered, middle class inmates being turned into prison bitches due to their lack of street skills or prison experience) Watching Oz, you may become comfortable with what is uncomfortable viewing....thats if you can get in touch with your darker side."

In [9]:
#Converting into lower case 
X = X.str.lower()
X[0]

"one of the other reviewers has mentioned that after watching just 1 oz episode you'll be hooked. they are right, as this is exactly what happened with me.<br /><br />the first thing that struck me about oz was its brutality and unflinching scenes of violence, which set in right from the word go. trust me, this is not a show for the faint hearted or timid. this show pulls no punches with regards to drugs, sex or violence. its is hardcore, in the classic use of the word.<br /><br />it is called oz as that is the nickname given to the oswald maximum security state penitentary. it focuses mainly on emerald city, an experimental section of the prison where all the cells have glass fronts and face inwards, so privacy is not high on the agenda. em city is home to many..aryans, muslims, gangstas, latinos, christians, italians, irish and more....so scuffles, death stares, dodgy dealings and shady agreements are never far away.<br /><br />i would say the main appeal of the show is due to the fact that it goes where other shows wouldn't dare. forget pretty pictures painted for mainstream audiences, forget charm, forget romance...oz doesn't mess around. the first episode i ever saw struck me as so nasty it was surreal, i couldn't say i was ready for it, but as i watched more, i developed a taste for oz, and got accustomed to the high levels of graphic violence. not just violence, but injustice (crooked guards who'll be sold out for a nickel, inmates who'll kill on order and get away with it, well mannered, middle class inmates being turned into prison bitches due to their lack of street skills or prison experience) watching oz, you may become comfortable with what is uncomfortable viewing....thats if you can get in touch with your darker side."

In [10]:
#removing html tags
X = X.apply(lambda x: BeautifulSoup(x, 'html.parser').get_text())
X[0]

"one of the other reviewers has mentioned that after watching just 1 oz episode you'll be hooked. they are right, as this is exactly what happened with me.the first thing that struck me about oz was its brutality and unflinching scenes of violence, which set in right from the word go. trust me, this is not a show for the faint hearted or timid. this show pulls no punches with regards to drugs, sex or violence. its is hardcore, in the classic use of the word.it is called oz as that is the nickname given to the oswald maximum security state penitentary. it focuses mainly on emerald city, an experimental section of the prison where all the cells have glass fronts and face inwards, so privacy is not high on the agenda. em city is home to many..aryans, muslims, gangstas, latinos, christians, italians, irish and more....so scuffles, death stares, dodgy dealings and shady agreements are never far away.i would say the main appeal of the show is due to the fact that it goes where other shows wouldn't dare. forget pretty pictures painted for mainstream audiences, forget charm, forget romance...oz doesn't mess around. the first episode i ever saw struck me as so nasty it was surreal, i couldn't say i was ready for it, but as i watched more, i developed a taste for oz, and got accustomed to the high levels of graphic violence. not just violence, but injustice (crooked guards who'll be sold out for a nickel, inmates who'll kill on order and get away with it, well mannered, middle class inmates being turned into prison bitches due to their lack of street skills or prison experience) watching oz, you may become comfortable with what is uncomfortable viewing....thats if you can get in touch with your darker side."

In [11]:
#removing punctuations
X = X.str.replace('[^\w\s]', '')
X[0]

"one of the other reviewers has mentioned that after watching just 1 oz episode you'll be hooked. they are right, as this is exactly what happened with me.the first thing that struck me about oz was its brutality and unflinching scenes of violence, which set in right from the word go. trust me, this is not a show for the faint hearted or timid. this show pulls no punches with regards to drugs, sex or violence. its is hardcore, in the classic use of the word.it is called oz as that is the nickname given to the oswald maximum security state penitentary. it focuses mainly on emerald city, an experimental section of the prison where all the cells have glass fronts and face inwards, so privacy is not high on the agenda. em city is home to many..aryans, muslims, gangstas, latinos, christians, italians, irish and more....so scuffles, death stares, dodgy dealings and shady agreements are never far away.i would say the main appeal of the show is due to the fact that it goes where other shows wouldn't dare. forget pretty pictures painted for mainstream audiences, forget charm, forget romance...oz doesn't mess around. the first episode i ever saw struck me as so nasty it was surreal, i couldn't say i was ready for it, but as i watched more, i developed a taste for oz, and got accustomed to the high levels of graphic violence. not just violence, but injustice (crooked guards who'll be sold out for a nickel, inmates who'll kill on order and get away with it, well mannered, middle class inmates being turned into prison bitches due to their lack of street skills or prison experience) watching oz, you may become comfortable with what is uncomfortable viewing....thats if you can get in touch with your darker side."

In [12]:
#removing urls
X = X.apply(lambda x: ' '.join([w for w in x.split() if 'http' not in w]))
X[0]

"one of the other reviewers has mentioned that after watching just 1 oz episode you'll be hooked. they are right, as this is exactly what happened with me.the first thing that struck me about oz was its brutality and unflinching scenes of violence, which set in right from the word go. trust me, this is not a show for the faint hearted or timid. this show pulls no punches with regards to drugs, sex or violence. its is hardcore, in the classic use of the word.it is called oz as that is the nickname given to the oswald maximum security state penitentary. it focuses mainly on emerald city, an experimental section of the prison where all the cells have glass fronts and face inwards, so privacy is not high on the agenda. em city is home to many..aryans, muslims, gangstas, latinos, christians, italians, irish and more....so scuffles, death stares, dodgy dealings and shady agreements are never far away.i would say the main appeal of the show is due to the fact that it goes where other shows wouldn't dare. forget pretty pictures painted for mainstream audiences, forget charm, forget romance...oz doesn't mess around. the first episode i ever saw struck me as so nasty it was surreal, i couldn't say i was ready for it, but as i watched more, i developed a taste for oz, and got accustomed to the high levels of graphic violence. not just violence, but injustice (crooked guards who'll be sold out for a nickel, inmates who'll kill on order and get away with it, well mannered, middle class inmates being turned into prison bitches due to their lack of street skills or prison experience) watching oz, you may become comfortable with what is uncomfortable viewing....thats if you can get in touch with your darker side."

In [13]:
#removing extra spaces
X = X.str.replace('\s+', ' ')
X[0]

"one of the other reviewers has mentioned that after watching just 1 oz episode you'll be hooked. they are right, as this is exactly what happened with me.the first thing that struck me about oz was its brutality and unflinching scenes of violence, which set in right from the word go. trust me, this is not a show for the faint hearted or timid. this show pulls no punches with regards to drugs, sex or violence. its is hardcore, in the classic use of the word.it is called oz as that is the nickname given to the oswald maximum security state penitentary. it focuses mainly on emerald city, an experimental section of the prison where all the cells have glass fronts and face inwards, so privacy is not high on the agenda. em city is home to many..aryans, muslims, gangstas, latinos, christians, italians, irish and more....so scuffles, death stares, dodgy dealings and shady agreements are never far away.i would say the main appeal of the show is due to the fact that it goes where other shows wouldn't dare. forget pretty pictures painted for mainstream audiences, forget charm, forget romance...oz doesn't mess around. the first episode i ever saw struck me as so nasty it was surreal, i couldn't say i was ready for it, but as i watched more, i developed a taste for oz, and got accustomed to the high levels of graphic violence. not just violence, but injustice (crooked guards who'll be sold out for a nickel, inmates who'll kill on order and get away with it, well mannered, middle class inmates being turned into prison bitches due to their lack of street skills or prison experience) watching oz, you may become comfortable with what is uncomfortable viewing....thats if you can get in touch with your darker side."

Tokenization

In [14]:
X = X.apply(word_tokenize)

In [15]:
X[0]

['one',
 'of',
 'the',
 'other',
 'reviewers',
 'has',
 'mentioned',
 'that',
 'after',
 'watching',
 'just',
 '1',
 'oz',
 'episode',
 'you',
 "'ll",
 'be',
 'hooked',
 '.',
 'they',
 'are',
 'right',
 ',',
 'as',
 'this',
 'is',
 'exactly',
 'what',
 'happened',
 'with',
 'me.the',
 'first',
 'thing',
 'that',
 'struck',
 'me',
 'about',
 'oz',
 'was',
 'its',
 'brutality',
 'and',
 'unflinching',
 'scenes',
 'of',
 'violence',
 ',',
 'which',
 'set',
 'in',
 'right',
 'from',
 'the',
 'word',
 'go',
 '.',
 'trust',
 'me',
 ',',
 'this',
 'is',
 'not',
 'a',
 'show',
 'for',
 'the',
 'faint',
 'hearted',
 'or',
 'timid',
 '.',
 'this',
 'show',
 'pulls',
 'no',
 'punches',
 'with',
 'regards',
 'to',
 'drugs',
 ',',
 'sex',
 'or',
 'violence',
 '.',
 'its',
 'is',
 'hardcore',
 ',',
 'in',
 'the',
 'classic',
 'use',
 'of',
 'the',
 'word.it',
 'is',
 'called',
 'oz',
 'as',
 'that',
 'is',
 'the',
 'nickname',
 'given',
 'to',
 'the',
 'oswald',
 'maximum',
 'security',
 'state',
 'penitentary',
 '.',
 'it',
 'focuses',
 'mainly',
 'on',
 'emerald',
 'city',
 ',',
 'an',
 'experimental',
 'section',
 'of',
 'the',
 'prison',
 'where',
 'all',
 'the',
 'cells',
 'have',
 'glass',
 'fronts',
 'and',
 'face',
 'inwards',
 ',',
 'so',
 'privacy',
 'is',
 'not',
 'high',
 'on',
 'the',
 'agenda',
 '.',
 'em',
 'city',
 'is',
 'home',
 'to',
 'many',
 '..',
 'aryans',
 ',',
 'muslims',
 ',',
 'gangstas',
 ',',
 'latinos',
 ',',
 'christians',
 ',',
 'italians',
 ',',
 'irish',
 'and',
 'more',
 '....',
 'so',
 'scuffles',
 ',',
 'death',
 'stares',
 ',',
 'dodgy',
 'dealings',
 'and',
 'shady',
 'agreements',
 'are',
 'never',
 'far',
 'away.i',
 'would',
 'say',
 'the',
 'main',
 'appeal',
 'of',
 'the',
 'show',
 'is',
 'due',
 'to',
 'the',
 'fact',
 'that',
 'it',
 'goes',
 'where',
 'other',
 'shows',
 'would',
 "n't",
 'dare',
 '.',
 'forget',
 'pretty',
 'pictures',
 'painted',
 'for',
 'mainstream',
 'audiences',
 ',',
 'forget',
 'charm',
 ',',
 'forget',
 'romance',
 '...',
 'oz',
 'does',
 "n't",
 'mess',
 'around',
 '.',
 'the',
 'first',
 'episode',
 'i',
 'ever',
 'saw',
 'struck',
 'me',
 'as',
 'so',
 'nasty',
 'it',
 'was',
 'surreal',
 ',',
 'i',
 'could',
 "n't",
 'say',
 'i',
 'was',
 'ready',
 'for',
 'it',
 ',',
 'but',
 'as',
 'i',
 'watched',
 'more',
 ',',
 'i',
 'developed',
 'a',
 'taste',
 'for',
 'oz',
 ',',
 'and',
 'got',
 'accustomed',
 'to',
 'the',
 'high',
 'levels',
 'of',
 'graphic',
 'violence',
 '.',
 'not',
 'just',
 'violence',
 ',',
 'but',
 'injustice',
 '(',
 'crooked',
 'guards',
 'who',
 "'ll",
 'be',
 'sold',
 'out',
 'for',
 'a',
 'nickel',
 ',',
 'inmates',
 'who',
 "'ll",
 'kill',
 'on',
 'order',
 'and',
 'get',
 'away',
 'with',
 'it',
 ',',
 'well',
 'mannered',
 ',',
 'middle',
 'class',
 'inmates',
 'being',
 'turned',
 'into',
 'prison',
 'bitches',
 'due',
 'to',
 'their',
 'lack',
 'of',
 'street',
 'skills',
 'or',
 'prison',
 'experience',
 ')',
 'watching',
 'oz',
 ',',
 'you',
 'may',
 'become',
 'comfortable',
 'with',
 'what',
 'is',
 'uncomfortable',
 'viewing',
 '....',
 'thats',
 'if',
 'you',
 'can',
 'get',
 'in',
 'touch',
 'with',
 'your',
 'darker',
 'side',
 '.']

In [16]:
#removing punctuations
X = X.apply(lambda x: [item for item in x if item not in string.punctuation])
X[0]

['one',
 'of',
 'the',
 'other',
 'reviewers',
 'has',
 'mentioned',
 'that',
 'after',
 'watching',
 'just',
 '1',
 'oz',
 'episode',
 'you',
 "'ll",
 'be',
 'hooked',
 'they',
 'are',
 'right',
 'as',
 'this',
 'is',
 'exactly',
 'what',
 'happened',
 'with',
 'me.the',
 'first',
 'thing',
 'that',
 'struck',
 'me',
 'about',
 'oz',
 'was',
 'its',
 'brutality',
 'and',
 'unflinching',
 'scenes',
 'of',
 'violence',
 'which',
 'set',
 'in',
 'right',
 'from',
 'the',
 'word',
 'go',
 'trust',
 'me',
 'this',
 'is',
 'not',
 'a',
 'show',
 'for',
 'the',
 'faint',
 'hearted',
 'or',
 'timid',
 'this',
 'show',
 'pulls',
 'no',
 'punches',
 'with',
 'regards',
 'to',
 'drugs',
 'sex',
 'or',
 'violence',
 'its',
 'is',
 'hardcore',
 'in',
 'the',
 'classic',
 'use',
 'of',
 'the',
 'word.it',
 'is',
 'called',
 'oz',
 'as',
 'that',
 'is',
 'the',
 'nickname',
 'given',
 'to',
 'the',
 'oswald',
 'maximum',
 'security',
 'state',
 'penitentary',
 'it',
 'focuses',
 'mainly',
 'on',
 'emerald',
 'city',
 'an',
 'experimental',
 'section',
 'of',
 'the',
 'prison',
 'where',
 'all',
 'the',
 'cells',
 'have',
 'glass',
 'fronts',
 'and',
 'face',
 'inwards',
 'so',
 'privacy',
 'is',
 'not',
 'high',
 'on',
 'the',
 'agenda',
 'em',
 'city',
 'is',
 'home',
 'to',
 'many',
 '..',
 'aryans',
 'muslims',
 'gangstas',
 'latinos',
 'christians',
 'italians',
 'irish',
 'and',
 'more',
 '....',
 'so',
 'scuffles',
 'death',
 'stares',
 'dodgy',
 'dealings',
 'and',
 'shady',
 'agreements',
 'are',
 'never',
 'far',
 'away.i',
 'would',
 'say',
 'the',
 'main',
 'appeal',
 'of',
 'the',
 'show',
 'is',
 'due',
 'to',
 'the',
 'fact',
 'that',
 'it',
 'goes',
 'where',
 'other',
 'shows',
 'would',
 "n't",
 'dare',
 'forget',
 'pretty',
 'pictures',
 'painted',
 'for',
 'mainstream',
 'audiences',
 'forget',
 'charm',
 'forget',
 'romance',
 '...',
 'oz',
 'does',
 "n't",
 'mess',
 'around',
 'the',
 'first',
 'episode',
 'i',
 'ever',
 'saw',
 'struck',
 'me',
 'as',
 'so',
 'nasty',
 'it',
 'was',
 'surreal',
 'i',
 'could',
 "n't",
 'say',
 'i',
 'was',
 'ready',
 'for',
 'it',
 'but',
 'as',
 'i',
 'watched',
 'more',
 'i',
 'developed',
 'a',
 'taste',
 'for',
 'oz',
 'and',
 'got',
 'accustomed',
 'to',
 'the',
 'high',
 'levels',
 'of',
 'graphic',
 'violence',
 'not',
 'just',
 'violence',
 'but',
 'injustice',
 'crooked',
 'guards',
 'who',
 "'ll",
 'be',
 'sold',
 'out',
 'for',
 'a',
 'nickel',
 'inmates',
 'who',
 "'ll",
 'kill',
 'on',
 'order',
 'and',
 'get',
 'away',
 'with',
 'it',
 'well',
 'mannered',
 'middle',
 'class',
 'inmates',
 'being',
 'turned',
 'into',
 'prison',
 'bitches',
 'due',
 'to',
 'their',
 'lack',
 'of',
 'street',
 'skills',
 'or',
 'prison',
 'experience',
 'watching',
 'oz',
 'you',
 'may',
 'become',
 'comfortable',
 'with',
 'what',
 'is',
 'uncomfortable',
 'viewing',
 '....',
 'thats',
 'if',
 'you',
 'can',
 'get',
 'in',
 'touch',
 'with',
 'your',
 'darker',
 'side']

In [17]:
#removing the stop words
from nltk.corpus import stopwords
stop_words = set(stopwords.words('english'))
X = X.apply(lambda x: [item for item in x if item not in stop_words])
X[0]

['one',
 'reviewers',
 'mentioned',
 'watching',
 '1',
 'oz',
 'episode',
 "'ll",
 'hooked',
 'right',
 'exactly',
 'happened',
 'me.the',
 'first',
 'thing',
 'struck',
 'oz',
 'brutality',
 'unflinching',
 'scenes',
 'violence',
 'set',
 'right',
 'word',
 'go',
 'trust',
 'show',
 'faint',
 'hearted',
 'timid',
 'show',
 'pulls',
 'punches',
 'regards',
 'drugs',
 'sex',
 'violence',
 'hardcore',
 'classic',
 'use',
 'word.it',
 'called',
 'oz',
 'nickname',
 'given',
 'oswald',
 'maximum',
 'security',
 'state',
 'penitentary',
 'focuses',
 'mainly',
 'emerald',
 'city',
 'experimental',
 'section',
 'prison',
 'cells',
 'glass',
 'fronts',
 'face',
 'inwards',
 'privacy',
 'high',
 'agenda',
 'em',
 'city',
 'home',
 'many',
 '..',
 'aryans',
 'muslims',
 'gangstas',
 'latinos',
 'christians',
 'italians',
 'irish',
 '....',
 'scuffles',
 'death',
 'stares',
 'dodgy',
 'dealings',
 'shady',
 'agreements',
 'never',
 'far',
 'away.i',
 'would',
 'say',
 'main',
 'appeal',
 'show',
 'due',
 'fact',
 'goes',
 'shows',
 'would',
 "n't",
 'dare',
 'forget',
 'pretty',
 'pictures',
 'painted',
 'mainstream',
 'audiences',
 'forget',
 'charm',
 'forget',
 'romance',
 '...',
 'oz',
 "n't",
 'mess',
 'around',
 'first',
 'episode',
 'ever',
 'saw',
 'struck',
 'nasty',
 'surreal',
 'could',
 "n't",
 'say',
 'ready',
 'watched',
 'developed',
 'taste',
 'oz',
 'got',
 'accustomed',
 'high',
 'levels',
 'graphic',
 'violence',
 'violence',
 'injustice',
 'crooked',
 'guards',
 "'ll",
 'sold',
 'nickel',
 'inmates',
 "'ll",
 'kill',
 'order',
 'get',
 'away',
 'well',
 'mannered',
 'middle',
 'class',
 'inmates',
 'turned',
 'prison',
 'bitches',
 'due',
 'lack',
 'street',
 'skills',
 'prison',
 'experience',
 'watching',
 'oz',
 'may',
 'become',
 'comfortable',
 'uncomfortable',
 'viewing',
 '....',
 'thats',
 'get',
 'touch',
 'darker',
 'side']

In [ ]:
#lemmitization
lemmatizer = WordNetLemmatizer()

X = X.apply(lambda words: [lemmatizer.lemmatize(word) for word in words])

In [ ]:
#cehcking the lemmitization of first review
X[0]

['one',
 'reviewer',
 'mentioned',
 'watching',
 '1',
 'oz',
 'episode',
 "'ll",
 'hooked',
 'right',
 'exactly',
 'happened',
 'me.the',
 'first',
 'thing',
 'struck',
 'oz',
 'brutality',
 'unflinching',
 'scene',
 'violence',
 'set',
 'right',
 'word',
 'go',
 'trust',
 'show',
 'faint',
 'hearted',
 'timid',
 'show',
 'pull',
 'punch',
 'regard',
 'drug',
 'sex',
 'violence',
 'hardcore',
 'classic',
 'use',
 'word.it',
 'called',
 'oz',
 'nickname',
 'given',
 'oswald',
 'maximum',
 'security',
 'state',
 'penitentary',
 'focus',
 'mainly',
 'emerald',
 'city',
 'experimental',
 'section',
 'prison',
 'cell',
 'glass',
 'front',
 'face',
 'inwards',
 'privacy',
 'high',
 'agenda',
 'em',
 'city',
 'home',
 'many',
 '..',
 'aryan',
 'muslim',
 'gangsta',
 'latino',
 'christian',
 'italian',
 'irish',
 '....',
 'scuffle',
 'death',
 'stare',
 'dodgy',
 'dealing',
 'shady',
 'agreement',
 'never',
 'far',
 'away.i',
 'would',
 'say',
 'main',
 'appeal',
 'show',
 'due',
 'fact',
 'go',
 'show',
 'would',
 "n't",
 'dare',
 'forget',
 'pretty',
 'picture',
 'painted',
 'mainstream',
 'audience',
 'forget',
 'charm',
 'forget',
 'romance',
 '...',
 'oz',
 "n't",
 'mess',
 'around',
 'first',
 'episode',
 'ever',
 'saw',
 'struck',
 'nasty',
 'surreal',
 'could',
 "n't",
 'say',
 'ready',
 'watched',
 'developed',
 'taste',
 'oz',
 'got',
 'accustomed',
 'high',
 'level',
 'graphic',
 'violence',
 'violence',
 'injustice',
 'crooked',
 'guard',
 "'ll",
 'sold',
 'nickel',
 'inmate',
 "'ll",
 'kill',
 'order',
 'get',
 'away',
 'well',
 'mannered',
 'middle',
 'class',
 'inmate',
 'turned',
 'prison',
 'bitch',
 'due',
 'lack',
 'street',
 'skill',
 'prison',
 'experience',
 'watching',
 'oz',
 'may',
 'become',
 'comfortable',
 'uncomfortable',
 'viewing',
 '....',
 'thats',
 'get',
 'touch',
 'darker',
 'side']

In [ ]:
#joining the words for  applying the bag of words vectorization
X = X.apply(lambda words: " ".join(words))
X[0]

"one reviewer mentioned watching 1 oz episode 'll hooked right exactly happened me.the first thing struck oz brutality unflinching scene violence set right word go trust show faint hearted timid show pull punch regard drug sex violence hardcore classic use word.it called oz nickname given oswald maximum security state penitentary focus mainly emerald city experimental section prison cell glass front face inwards privacy high agenda em city home many .. aryan muslim gangsta latino christian italian irish .... scuffle death stare dodgy dealing shady agreement never far away.i would say main appeal show due fact go show would n't dare forget pretty picture painted mainstream audience forget charm forget romance ... oz n't mess around first episode ever saw struck nasty surreal could n't say ready watched developed taste oz got accustomed high level graphic violence violence injustice crooked guard 'll sold nickel inmate 'll kill order get away well mannered middle class inmate turned prison bitch due lack street skill prison experience watching oz may become comfortable uncomfortable viewing .... thats get touch darker side"

In [ ]:
#applying bag of words
vectorizer = CountVectorizer()

X_features = vectorizer.fit_transform(X)
X_features

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 4879289 stored elements and shape (50000, 97429)>

Encoding the Target Variable

In [ ]:
#encoding the target variable byusing the label encoder
from sklearn.preprocessing import LabelEncoder

encoder = LabelEncoder()

y = encoder.fit_transform(y)
y

array([1, 1, 1, ..., 0, 0, 0])

Train Test Split The Data

In [ ]:
#traing test split the data
X_train, X_test, y_train, y_test = train_test_split(
    X_features,
    y,
    test_size=0.2,
    random_state=42
)

checking the shape of the training and testing data

In [ ]:
#printing the shape of the train and test data
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(40000, 97429)
(10000, 97429)
(40000,)
(10000,)

selecting models

In [ ]:
#Naive Bayes
naive_bayes = MultinomialNB()
#Logistic Regression
logistic_regression = LogisticRegression(max_iter=1000)

traning naive bayes algorithim

In [ ]:
#Training Naive Bayes 
naive_bayes.fit(X_train, y_train)

MultinomialNB()

training logistic regression algorithim

In [ ]:
#Training Logistic Regression
logistic_regression.fit(X_train, y_train)

LogisticRegression(max_iter=1000)

predictions

In [ ]:
#Naive Bayes and Logistic Regression Prediction
nb_prediction = naive_bayes.predict(X_test)
lr_prediction = logistic_regression.predict(X_test)

Accuarcy

In [ ]:
#Accuracy of Naive Bayes and Logistic Regression
nb_accuracy = accuracy_score(y_test, nb_prediction)

print("Naive Bayes Accuracy :", nb_accuracy)
lr_accuracy = accuracy_score(y_test, lr_prediction)

print("Logistic Regression Accuracy :", lr_accuracy)

Naive Bayes Accuracy : 0.8573
Logistic Regression Accuracy : 0.884

Results

In [ ]:
#Comparing the Accuracy
results = pd.DataFrame({
    "Model": ["Naive Bayes", "Logistic Regression"],
    "Accuracy": [nb_accuracy, lr_accuracy]
})

results

                 Model  Accuracy
0          Naive Bayes    0.8573
1  Logistic Regression    0.8840

User Input for more reviews.

In [ ]:
from better_profanity import profanity
# Load profanity words
profanity.load_censor_words()

# Stopwords
stop_words = set(stopwords.words('english'))

# Keep important negation words
stop_words.discard("not")
stop_words.discard("no")
stop_words.discard("never")

# Lemmatizer
lemmatizer = WordNetLemmatizer()

def predict_sentiment():

    # ===========================
    # Step 1: Take User Input
    # ===========================
    review = input("Enter your movie review: ")

    # ===========================
    # Step 2: Check for Abusive Words
    # ===========================
    if profanity.contains_profanity(review):
        print("\n⚠️ Your review contains abusive or offensive language.")
        print("Please use respectful language and try again.")
        return

    # ===========================
    # Step 3: Lowercase
    # ===========================
    review = review.lower()

    # ===========================
    # Step 4: Remove HTML Tags
    # ===========================
    review = BeautifulSoup(review, "html.parser").get_text()

    # ===========================
    # Step 5: Remove URLs
    # ===========================
    review = re.sub(r'http\S+|www\S+', '', review)

    # ===========================
    # Step 6: Remove Punctuation
    # ===========================
    review = review.translate(str.maketrans('', '', string.punctuation))

    # ===========================
    # Step 7: Remove Numbers
    # ===========================
    review = re.sub(r'\d+', '', review)

    # ===========================
    # Step 8: Remove Extra Spaces
    # ===========================
    review = " ".join(review.split())

    # ===========================
    # Step 9: Tokenization
    # ===========================
    words = review.split()

    # ===========================
    # Step 10: Remove Stopwords
    # ===========================
    words = [word for word in words if word not in stop_words]

    # ===========================
    # Step 11: Lemmatization
    # ===========================
    words = [lemmatizer.lemmatize(word) for word in words]

    # ===========================
    # Step 12: Join Words
    # ===========================
    review = " ".join(words)

    # ===========================
    # Step 13: Vectorization
    # ===========================
    review_vector = vectorizer.transform([review])

    # ===========================
    # Step 14: Prediction
    # ===========================
    prediction = logistic_regression.predict(review_vector)

    # ===========================
    # Step 15: Display Result
    # ===========================
    if prediction[0] == 1:
        print("\nPrediction: 😊 Positive")
    else:
        print("\nPrediction: 😞 Negative")


# Run the function
predict_sentiment()

Prediction: 😞 Negative